### ISSUE TITLE
Optionally get source image from Plex

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#141]
Ability to use Plex-embedded thumbnail as source image should be added.

Perhaps some priority setting for when to use which method, like:

```yaml
# global preferences
options:
  source_priority: tmdb | plex | tmdb, plex | plex, tmdb
```

So the user could select which methods they want to utilize _first_. The above syntax would optionally enable/disable source methods (also pretty versatile for the future if additional source gathering methods are added).

If TMDb takes priority over Plex, two options for the logic:
- The Plex image could be used until a TMDb image is found (and is used immediately after failure to find a TMDb image)
- The Plex image is only used after a source image request has failed more than the blacklist threshold
