### ISSUE TITLE
Create series and/or season posters

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#144]
Add some functionality to create series/season posters.

Could take in/query TMDb for textless posts, add logo to fixed position, and add some season text beneath that.

Haven't determined how this behavior would be specified.

**Comment by CollinHeist** [comment]
Working on this, I've got a working custom font and generic font version:

# Generic Font
## Image
<img src="https://user-images.githubusercontent.com/17693271/172294407-2a6f67c3-2ce8-4f68-a846-2cb05bd827ff.png" height="600"/>

## Command
```console
convert "season1.jpg" -resize 1000x1500 \( "gradient.png" -resize 1000x1500! \) -composite -gravity south \( "logo.png" -resize 730x \) -geometry +0+178 -composite -font "Proxima Nova Semibold.otf" -fill "#CFCFCF" -pointsize 40 -kerning 15 -annotate +0+106 "SEASON ONE" out.png
```

# Custom Font
## Image
<img src="https://user-images.githubusercontent.com/17693271/172294392-ecababbe-eeef-4e28-b08c-814b7e02f4c7.png" height="600"/>

## Command
```console
convert "season1.jpg" -resize 1000x1500 \( "gradient.png" -resize 1000x1500! \) -composite -gravity south \( "logo.png" -resize 730x \) -geometry +0+178 -composite -font "Proxima Nova Semibold.otf" -fill "#D12D27" -pointsize 40 -kerning 15 -annotate +0+106 "SEASON_1.0" out.png
```

**Comment by CollinHeist** [comment]
So if customized fonts are to be supported, then kerning, font size, and color will need to be adjustable at a minimum

**Comment by CollinHeist** [comment]
Haven't decided the best way to specify whether or not to create these. I think it should be disabled by default (a lot of people might manually specify assets). Working idea:

```yaml
series:
  Mr. Robot:
    year: 2016
    # etc.
    seasons:
      posters:
        create: true
        font:
          file: ./path/to/some/file.ext
          color: "#hex"
      1: season_1.0
      2: season_2.0
      # etc.
```

Should always use `season{number}.jpg` (i.e. `season1.jpg`) within source directory as source image.

Use the season title indicated within the season subsection (so `season_text="season_1.0"`, etc.).

**Comment by Wdvh** [comment]
I'm thinking use only manually added images there is so much falsely declared stuff on TMDb in the poster section. If no season title is found use standards if they are use them.

**Comment by CollinHeist** [comment]
So the downside to the above implementation is that season posters couldn't be created if episode ranges were used.

I think this subsection should be moved out of the `seasons` attribute (also removes a layer of nesting..), and allowing for manually specified titles (would override all other title specifications) is best. Something like:

```yaml
series:
  Mr. Robot:
    year: 2016
    # etc.
    season_posters:
      create: true
      titles:
        1: season_1.0
        2: season_2.0
      font:
          file: ./path/to/some/file.ext
          color: "#hex"
    episode_ranges:
      1-10: different title
      # etc.
```
