### ISSUE TITLE
Let arbitrary series-wide data be passed to TitleCard object

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#147]
Similar to episode arbitrary extra characteristics, series unspecified data should be passed to `TitleCard` creation  as well.

For example:

```yaml
series:
  TV Show:
    year: xxxx
    extras:
      logo_file: logo.png
      background: black
```

Would pass:
```python
{'logo_file': 'logo.png', 'background': 'black'}
```
To the `TitleCard.__init__()` method. This makes custom card types more versatile
