### ISSUE TITLE
FEATURE - Allow for multiple translations per series

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#179]
Multiple translations should be allowed per-series. It's currently cumbersome to have a translated preferred title _and_ utilize kanji for the `AnimeTitleCard`. Currently this can be done with duplicate series YAML entries with different translations, like so:

```yaml
series:
  Attack on Titan:
    year: 2013
    archive: false
    translation:
      language: ja
      key: kanji

  Attack on Titan 2:
    title: Attack on Titan
    year: 2013
    library: # bla bla
    translation:
      language: french
      key: preferred_title
    extras:
      require_kanji: true
```

But obviously that's very messy. It should be possible within a single series, like so:

```yaml
series:
  Attack on Titan:
    year: 2013
    library: # bla bla
    translation:
    - language: french
      key: preferred_title
    - language: ja
      key: kanji
    extras:
      require_kanji: true
```

Which (partly) yields the following object:
```python
{'translation': [{'language': 'fr', 'key': 'preferred_title'}, {'language': 'ja', 'key': 'kanji'}]}
```
