### ISSUE TITLE
BUG - Unraid Install Unable to Pull Source Images From Plex

### ISSUE THREAD

**Issue by fkick** [CollinHeist/TitleCardMaker#183]
### Installation

Docker - master tag

### Describe the Bug

When Plex is set as the only source using source_priority key, TitleCardMaker is hanging after generating the data.yml file and not pulling source images from Plex.

If TMDB is listed as a source (either along or as second priority), cards are built as expected, but only by ignoring those in plex.

### Expected Behavior

Source images are pulled from Plex server and Title cards are generated

### Steps to reproduce the behavior

1. Setup TitleCardMaker on Unraid 
2. Set source_priority key in preferences.yml to "plex"3. 
3. Setup Plex URL and Token in preferences.yml
4. In tv.yml setup library to match Plex Library information 
5. Run the docker.

### Screenshots
<img width="996" alt="Screen Shot 2022-06-14 at 9 11 23 AM" src="https://user-images.githubusercontent.com/8224667/173598316-4ae60b9b-c8a6-423b-b7a8-bdb421e99545.png">

### Preference File

```yaml
options:
  source: /config/source/
  series: /config/tv.yml
  card_type: standard

#archive:
 # path: /config/archives/
  
plex:
  url: http://192.168.1.15:32400/
  token: **REDACTED**

source_priority: plex

sonarr:
  url:  **REDACTED**
  api_key: **REDACTED**

#tmdb:
 # api_key:  **REDACTED**
```

### Series YAML

```yaml
libraries:
  TV Shows:
    path: /TV/
    plex_name: "TV Shows"

  #Anime:
   # path: YOUR_MEDIA_DIRECTORY/Anime/
    #card_type: anime

series:
  Star Trek Discovery:
    year: 2017
    library: TV Shows
    media_directory: /TV/Star Trek Discovery/
    font:
      color: "#f3910e"
      file: /config/fonts/trek.ttf
      replacements:
        …: ...
```

### Debug Log

[CRITICAL] [22-06-13 15:46:49] Preference file "/config/preferences.yml" does not exist [CRITICAL] [22-06-13 15:47:04] Preference file "/config/preferences.yml" does not exist [CRITICAL] [22-06-13 16:09:58] Preference file "/config/preferences.yml" does not exist [CRITICAL] [22-06-13 16:10:29] Preference file "/config/preferences.yml" does not exist [INFO] [22-06-13 16:14:10] Read preference file "/config/preferences.yml" [DEBUG] [22-06-13 16:14:12] Using "" ImageMagick command prefix [ERROR] [22-06-13 16:14:13] Series file "/config/tv.yml" does not exist [INFO] [22-06-13 16:14:13] Wrote missing assets to "missing.yml" [INFO] [22-06-13 16:14:13] Starting first run in 20746 seconds [INFO] [22-06-13 16:33:55] Read preference file "/config/preferences.yml" [DEBUG] [22-06-13 16:33:57] Using "" ImageMagick command prefix [ERROR] [22-06-13 16:33:59] Series file "/config/tv.yml" does not exist [INFO] [22-06-13 16:33:59] Wrote missing assets to "missing.yml" [INFO] [22-06-13 16:33:59] Starting first run in 19560 seconds [INFO] [22-
