### ISSUE TITLE
BUG - Unraid Install not generating missing.yml

### ISSUE THREAD

**Issue by fkick** [CollinHeist/TitleCardMaker#184]
### Installation

Docker - master tag

### Describe the Bug

Maker.log shows that "Wrote Missing Assets to 'missing.yml' however now missing.yml is created at /config/missing.yml

### Expected Behavior

Missing.yml would be created

### Steps to reproduce the behavior

Run TitleCardMaker on series that has missing assets

### Preference File

```yaml
options:
  source: /config/source/
  series: /config/tv.yml
  card_type: standard

#archive:
 # path: /config/archives/
  
plex:
  url: **REDACTED**
  token: **REDACTED**

source_priority: plex

sonarr:
  url:  **REDACTED**
  api_key: **REDACTED**

#tmdb:
 # api_key:  **REDACTED**
```

### Series YAML

```yaml
libraries:
  TV Shows:
    path: /TV/
    #plex_name: "TV Shows"

  #Anime:
   # path: YOUR_MEDIA_DIRECTORY/Anime/
    #card_type: anime

series:
  Star Trek Discovery:
    year: 2017
    library: TV Shows
    media_directory: /TV/Star Trek Discovery/
    font:
      color: "#f3910e"
      file: /config/fonts/trek.ttf
      replacements:
        …: ...
```

### Debug Log

[INFO] [22-06-14 08:37:28] Read preference file "/config/preferences.yml" [DEBUG] [22-06-14 08:37:28] Using "" ImageMagick command prefix [INFO] [22-06-14 08:37:30] Wrote missing assets to "missing.yml" [INFO] [22-06-14 08:37:30] Starting first run in 48149 seconds [INFO] [22-06-14 08:39:02] Read preference file "/config/preferences.yml" [DEBUG] [22-06-14 08:39:02] Using "" ImageMagick command prefix [INFO] [22-06-14 08:39:04] Added 58 episodes to "Star Trek Discovery (2017)" [INFO] [22-06-14 08:47:09] Read preference file "/config/preferences.yml" [DEBUG] [22-06-14 08:47:11] Using "" ImageMagick command prefix [INFO] [22-06-14 08:47:13] Added 58 episodes to "Star Trek Discovery (2017)" [INFO] [22-06-14 09:03:01] Read preference file "/config/preferences.yml" [DEBUG] [22-06-14 09:03:01] Using "" ImageMagick command prefix [INFO] [22-06-14 09:03:03] Added 58 episodes to "Star Trek Discovery (2017)" [INFO] [22-06-14 09:03:04] Wrote missing assets to "missing.yml" [INFO] [22-06-14 09:03:04] Starting first run in 46615 seconds [INFO] [22-06-14 12:48:29] Read preference file "/config/preferences.yml" [DEBUG] [22-06-14 12:48:31] Using "" ImageMagick command prefix [INFO] [22-06-14 12:48:34] Wrote missing assets to "missing.yml" [INFO] [22-06-14 12:48:34] Starting first run in 33085 seconds [INFO] [22-06-14 12:58:20] Read preference file "/config/preferences.yml" [DEBUG] [22-06-14 12:58:21] Using "" ImageMagick command prefix [INFO] [22-06-14 12:58:23] Added 58 episodes to "Star Trek Discovery (2017)" [INFO] [22-06-14 12:58:24] Wrote missing assets to "missing.yml" [INFO] [22-06-14 12:58:24] Starting first run in 32495 seconds [INFO] [22-06-14 13:11:59] Read preference file "/config/preferences.yml" [DEBUG] [22-06-14 13:12:01] Using "" ImageMagick command prefix [INFO] [22-06-14 13:12:04] Wrote missing assets to "missing.yml" [INFO] [22-06-14 13:12:04] Starting first run in 31675 seconds
