### ISSUE TITLE
Deepcopy templates before application

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#193]
If a template has recursive structures (like `extras`) then those objects are modified and then not applied to subsequent instances of that template. For example:

```yaml
templates:
  reality-tv:
    year: <<year>>
    card_type: reality tv
    extras:
      logo: ./source/<<title>> (<<year>>)/logo.png
      background: <<background>>

series:
  MasterChef (US):
    template: {
      name: reality-tv, 
      year: 2010, 
      title: MasterChef (US), 
      background: black
      }

  The Challenge:
    template: {
      name: reality-tv, 
      year: 1998, 
      title: The Challenge, 
      background: black
      }
```

The first application of the `reality-tv` template would result in the nested `extras` dictionary becoming:

```yaml
extras:
  logo: ./source/MasterChef (US) (2010)/logo.png
  background: black
```

Which then has no keys to modify, resulting in the wrong logo (and background, technically) from being applied.

---

Solution is pretty easy, just use `copy.deepcopy` instead of built-in `copy`.
