### ISSUE TITLE
Improve specifying different archival card types

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#196]
If you want to archive a series in different card types, currently that requires multiple entries in the YAML and can be very inefficient/messy.

A modification of the template to permit multiple templates could be used. Two possible implementations are:

```yaml
series:
  Obi-Wan Kenobi:
    template:
      name: chapters, normal, absolute 
      year: 2022
# option 2
  Obi-Wan Kenobi:
  - template: {name: chapters, year: 2022}
  - template: {name: normal, year: 2022}
  - template: {name: absolute, year: 2022}
```

The first specified template could be used for within Plex, the rest treated as archives.. However, I don't love "forcing" the user to use a template so perhaps it should just be a function of the `card_type` identifier that allows for lists?

It's also problematic if the user wants to specify customized elements other than the card_type and whether those are applied to the archives as well..

**Comment by CollinHeist** [comment]
I think rather than burying this functionality in the template specification, a new option `archive_variations` should parsed. This could be specified like:
```yaml
series:
  Obi-Wan Kenobi:
    # normal series stuff
    archive_variations:
    - card_type: logo
    - card_type: star wars
       episode_text_format: Chapter {abs_number}
    - # etc.
```
This could take a list of variations, each of which defaults to the entire base series YAML (post template application) - with the exception of `library` and `media_directory` - and then be overwritten by whatever attributes _are_ specified.

Although slightly more verbose than the original suggestion; it has the benefit of not confusing or complicating the template functionality, nor does it require the user to use templates at all. Could technically be specified very succinctly like:
```yaml
series:
  Obi-Wan Kenobi:
    # stuff
    archive_variations: [card_type: logo, {card_type: star wars, episode_text_format: "Chapter {abs_number}"}]
```

---

Code-wide, this would be a part of the `PreferenceParser.iterate_series_files()` method. Yielding new `Show` objects with YAML modified by each given variation.
