### ISSUE TITLE
Setup Problem - No Files being generated

### ISSUE THREAD

**Issue by Nepadeus** [CollinHeist/TitleCardMaker#198]
### Installation

GitHub - master branch

### Describe the Bug

When running "pipenv run python main.py --run" via PowerShell the program executes fine, creating folders if missing, runnings its scripts. 
Title cards are being downloaded from tmdb or plex , but no Files are being created in the series folder or archive folder. 
The archive folder structure is being created, but remains empty.
Docker Log of ImageMagick is empty.

### Expected Behavior

Creation of Title Cards with build-in Card-Types

### Steps to reproduce the behavior

1. Following Step 1 to 4 of the Introduction
2. Installing ImageMagick on Windows
3. Installing TitleCardMaker
4. Following Step 7 to 12
5. When running with ImageMagick on Windows i get 

> Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\TitleCardMaker\fixer.py", line 122, in <module>
    pp = PreferenceParser(args.preferences)
  File "C:\Users\Administrator\Documents\TitleCardMaker\modules\PreferenceParser.py", line 92, in __init__
    self.__determine_imagemagick_prefix()
  File "C:\Users\Administrator\Documents\TitleCardMaker\modules\PreferenceParser.py", line 114, in __determine_imagemagick_prefix
    font_output = imi.run_get_output(f'convert -list font')
  File "C:\Users\Administrator\Documents\TitleCardMaker\modules\ImageMagickInterface.py", line 113, in run_get_output
    return b''.join(self.run(command)).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 5: invalid continuation byte
6. Installing ImageMagick on Docker
7. Running the program seemingly fine
8. Getting this missing.yml and no generated Files

> '"Arcane (2021)"':
  Episode S01E01:
    card: Arcane (2021) - S01E01.jpg
  Episode S01E02:
    card: Arcane (2021) - S01E02.jpg
  Episode S01E03:
    card: Arcane (2021) - S01E03.jpg
  Episode S01E04:
    card: Arcane (2021) - S01E04.jpg
  Episode S01E05:
    card: Arcane (2021) - S01E05.jpg
  Episode S01E06:
    card: Arcane (2021) - S01E06.jpg
  Episode S01E07:
    card: Arcane (2021) - S01E07.jpg
  Episode S01E08:
    card: Arcane (2021) - S01E08.jpg
  Episode S01E09:
    card: Arcane (2021) - S01E09.jpg

### Screenshots

![image](https://user-images.githubusercontent.com/70981140/174858200-d4cb26ed-23cf-4013-936d-56fb90cbd7e6.png)
![image](https://user-images.githubusercontent.com/70981140/174860168-92e12b96-b3c9-4f68-b7bd-ee1567adffb8.png)

### Preference File

```yaml
options:
  source: source
  source_priority: plex, tmdb
  series: ./tv.yml
  card_type: standard
archive:
  path: ./archives/
  
plex:
  url: http://MYIP:32400
  token: yyZVB1MQZEmiKgv5go77

sonarr:
  url: http://MYIP/sonarr/api/v3/
  api_key: APIKEY

tmdb:
  api_key: APIKEY
  
imagemagick:
  container: imageedit
```

### Series YAML

```yaml
libraries:
  Other Serien:
    path: D:\Other Serien
    plex_name: Other Series
series:
    Arcane:
        year: 2021
        library: Other Series
```

### Debug Log

https://github.com/Nepadeus/cloud/blob/f12632e84415f7f271f1196a527fc7805b97448f/maker.log
