### ISSUE TITLE
BUG - Logo file path not sent to custom card types

### ISSUE THREAD

**Issue by dhicock** [CollinHeist/TitleCardMaker#199]
### Installation

Docker - master tag

### Describe the Bug

When specifying the logo in tv.yml, it should just go under `logo:` or `logo_filename:` but neither works. It always says "Logo file not specified"

This is for Beedman/GradientLogoTitleCard, and I may be misunderstanding how the custom card types work, but this does not work.

### Expected Behavior

Logo is used

### Steps to reproduce the behavior

1. Add a new show with the card type Beedman/GradientLogoTitleCard
2. Run script
3. See error message

### Screenshots

![image](https://user-images.githubusercontent.com/5377881/175166909-1ee654fb-617e-4762-99b4-34eca46efd27.png)

### Preference File

```yaml
options:
  source: /config/source/
  series: /config/tv.yml

archive:
  path: /config/archives/
  
plex:
  url: http://*.*.*.*:32400/
  token: *************************

sonarr:
  url: http://*.*.*.*:8989/api/v3/
  api_key: *************************

tmdb:
  api_key: *************************
```

### Series YAML

```yaml
libraries:
  TV Shows:
    path: /tv
    plex_name: "TV Shows"
    card_type: standard

series:
  The Boys:
    year: 2019
    library: "TV Shows"
    logo: /config/logos/The Boys (2019)/logo.png
    font:
      color: "#FFFFFF"
      file: /config/fonts/CHARLIE DONT SURF.ttf
    card_type: Beedman/GradientLogoTitleCard
```

### Debug Log

N/A

**Comment by CollinHeist** [comment]
You need to specify the logo, see [here](https://github.com/CollinHeist/TitleCardMaker-CardTypes/tree/master/Beedman#specification).

```yaml
series:
  The Boys:
    year: 2019
    library: "TV Shows"
    font:
      color: "#FFFFFF"
      file: /config/fonts/CHARLIE DONT SURF.ttf
    card_type: Beedman/GradientLogoTitleCard
    extras:
      logo: /config/logos/The Boys (2019)/logo.png
```
