### ISSUE TITLE
Optionally get episode data from Plex or TMDb

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#201]
Ability to get episode data from either Plex or TMDb should be permitted.

Ideally, Sonarr would be preferred (because of inherent matching benefits), but non-Sonarr series or non-TVDb-aligned series should be allowed.

Probably use YAML like:

```yaml
series:
  Breaking Bad:
    episode_data_source: sonarr | tmdb | plex
```
