### ISSUE TITLE
Add ability to sync all series within Sonarr or Plex to some series YAML file 

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#224]
# Background
Similar to the existing fixer functionality of `--read-all-series`, there should be the ability to sync all series from either Plex or Sonarr into a series YAML file so title cards can be created for them automatically.

# Notes
Specification should be mutually exclusive, so either Plex _or_ Sonarr.

The biggest hurdle will be determining/specifying valid media directories, as a lot (probably most) users are likely using containers, where the paths of TCM ≠ the paths of the media manager.

First pass of how this could be implemented (with options described below):

# Plex
```yaml
plex:
  url: ...
  token: ... 
  sync:
    file: ./yaml/plex_sync.yml
    mode: append | [sync]
    compact_mode: [true] | false
    libraries: # If not present, sync all
    - TV Shows
    - Anime
    - TV 4K 
    volumes: 
      /plex/media/tv/: /maker/media/tv
      # Other docker volume mappings
```

# Sonarr
```yaml
sonarr:
  url: ...
  api_key: ...
  sync:
    file: ./yaml/sonarr_sync.yml
    mode: append | [sync]
    compact_mode: [true] | false
    monitored_only: true | [false]
    tags: # If not present, sync all
    - downloaded
    volumes:
      /sonarr/media/tv: /maker/media/tv
      # Other docker volume mappings
    plex_libraries:
      /maker/media/tv: TV
      /maker/media/anime: anime
```

**Comment by CollinHeist** [comment]
I think there should be a toggle-able "compact" mode, like:
```yaml
compact_mode: false | [true]
```
Compact mode would look like:
```yaml
series:
  Breaking Bad: {year: 2008, library: TV, imdb_id: tt1234, tvdb_id: 1234 ... }
```
While verbose (not compact) mode would look more standard, like:
```yaml
series:
  Breaking Bad:
    year: 2008
    library: TV
    imdb_id: tt1234
    tvdb_id: 1234
    # ...
```
