### ISSUE TITLE
Overhaul archives

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#233]
Archives have a multitude of QOL issues, namely:

- It is not possible to keep two separate archives of the same card type - such as one in black font, another white
- It is not possible to have a "custom named" archive
- Cards are always archived in the watched style of the series
- A more behind the scenes problem is that profiles are weird, and individual card types cannot control their sub-variations (such as AnimeTitleCard archiving a kanji- and kanji-less variation).

---

To address this, some fixes should be made:

1. Allow archives to be uniquely named by optionally specifying an archive name
   - This could apply to a series or archive variations:
     ```yaml
     series:
       Mr. Robot:
         year: 2015
         card_type: standard
         archive_name: Standard Cards
         archive_variations:
         - card_type: roman
           archive_name: Roman Numeral Cards
     ```
   - If _specified_, no sub-variations for that archive should be created (unless also listed under `archive_variations`)
   - If _unspecified_, TCM should act as it currently does
2. Allow for specification of a specific style by specifying `archive_style` like so:
    ```yaml
    series:
    Mr. Robot:
        year: 2015
        watched_style: unique
        unwatched_style: blur
        archive_style: art | blur | unique # Defaults to [watched_style]
    ```

Not sure how to address point 4 yet

**Comment by CollinHeist** [comment]
All variations should also be toggle-able per-series, as:
```yaml
series:
  Breaking Bad:
    year: 2008
    archive:
      all_variations: true | false # Defaults to [global default]
```
