### ISSUE TITLE
Allow specification of series/tags to exclude from Series YAML sync

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#238]
Series that users don't want to make cards for should be exclude-able from YAML sync.

Both Plex and Sonarr should take either a list of series names, or a file to a list of series names to exclude. Exclusion should be like:

```yaml
sonarr | plex:
  # ...
  sync:
    exclusions:
    - yaml: /path/to/series_yaml_file.yml
    - tag: exclude_tag1 # Only for Sonarr
    - series: Breaking Bad (2008)
    - # ...
```
Each exclusion would be:
- `yaml` would be a filepath to a series YAML file that would be ignored from sync
- `tag` Sonarr tag to exclude from sync
- `series` Series _full name_ to exclude from sync

This gives good flexibility for excluding individual or many series
