### ISSUE TITLE
Optionally add templates to series YAML sync

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#239]
Templates should be optionally auto-added to synced YAML, for those that use templates to the default season titles, language, etc.

Could be easy to just add `template` option, probably not feasible to auto-add arguments or anything. Suggested in the Discord to add template based on Sonarr tags, which is an interesting idea - but I can't think of a realistic use case for this.

---

For now, easiest implementation would be:

```yaml
sonarr | plex:
  # ...
  sync:
    add_template: example_template
``` 
Which would produce YAML like:
```yaml
series:
  Breaking Bad: {year: 2008, library: TV, template: example_template}
```
