### ISSUE TITLE
Optionally disable SSL certificate verification with Sonarr

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#241]
Ability to disable certificate validation should be provided so OS/containers without valid certificates can make signed requests to Sonarr.

Probably enabled via `verify_ssl` boolean option:
```yaml
sonarr:
  url: # 
  api_key: #
  verify_ssl: true | [false]
```
