### ISSUE TITLE
Allow for specification of multiple series YAML syncs

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#243]
It can be useful to have different configurations of the series YAML sync to different files - whether that's for different templates, card types, etc.

To permit this, the YAML sync should also permit specification as a list, like so:
```yaml
sonarr:
  url: http://192.168.0.29:8989/api/v3/
  api_key: d43fdeb9c3744f58b1ffbaf5dc21e55a
  sync:
  - file: ./yml/sonarr_sync_ongoing.yml
    template: ongoing
    required_tags:
    - ongoing
    exclusions:
    - yaml: ./yml/exclusions.yml
    plex_libraries:
      /mnt/user/Media/TV Shows/: TV Shows
      /mnt/user/Media/Anime/: Anime
  - file: ./yml/sonarr_sync_ended.yml
    template: ended
    required_tags:
    - ended
    exclusions:
    - yaml: ./yml/exclusions.yml
    plex_libraries:
     /mnt/user/Media/TV Shows/: TV Shows
     /mnt/user/Media/Anime/: Anime
```

This would effectively sync two files `sonarr_sync_ongoing` with series tagged `ongoing` in Sonarr, and `sonarr_sync_ended` with the series tagged `ended`. Obviously other use cases would be possible.

Should also be possible with Plex sync, although it seems much less useful since tagging isn't present.

**Comment by CollinHeist** [comment]
To avoid having to specify static information, each option that isn't specified as a part of a list should apply to all subsequent specifications, like:
```yaml
sonarr:
  url: http://192.168.0.29:8989/api/v3/
  api_key: d43fdeb9c3744f58b1ffbaf5dc21e55a
  sync:
    volumes:
      /sonarr/path/: /tcm/path/
    plex_libraries:
     /mnt/user/Media/TV Shows/: TV Shows
     /mnt/user/Media/Anime/: Anime
    exclusions:
    - yaml: ./yml/exclusions.yml
  - file: ./yml/sonarr_sync_ongoing.yml
    template: ongoing
    required_tags:
    - ongoing
  - file: ./yml/sonarr_sync_ended.yml
    template: ended
    required_tags:
    - ended
```

Would be effectively the same as having repeated the volumes, plex_libraries, and exclusions for each sync
