### ISSUE TITLE
BUG - Unable to write to network drive

### ISSUE THREAD

**Issue by azuravian** [CollinHeist/TitleCardMaker#247]
### Installation

GitHub - master branch

### Describe the Bug

When running, Maker completes its process but no images show up in network folder.  Log contains following error for final step of each image:

```
[DEBUG] [22-08-22 10:16:02] Command: magick composite -gravity southwest -geometry +50+50 "I:\Portable Apps\TitleCardMaker\modules\.objects\series_count_text.png" "I:\Portable Apps\TitleCardMaker\modules\.objects\gradient_title.png" "\\192.168.68.109\QNAP\Multimedia\TV\Mr. Mercedes\Season 1\Mr. Mercedes (2017) - S01E01.jpg"

stdout: b''

stderr: b"composite: unable to open image '\\192.168.68.109\\QNAP\\Multimedia\\TV\\Mr. Mercedes\\Season 1\\Mr. Mercedes (2017) - S01E01.jpg': No such file or directory @ error/blob.c/OpenBlob/3537.\r\n"
```

I can run this same command from the same terminal window that I run maker from and it creates the image with no error.

### Expected Behavior

Images would be created inside media folder on network drive.

### Preference File

```yaml
options:
  source: ./source/
  series: ./tv.yml
  card_type: standard

archive:
  path: ./archives/
  
plex:
  url: [[url]]
  token: [[token]]

sonarr:
  url: [[url]]
  api_key: [[key]]
  sync:
  - mode: append
    compact_mode: false
    plex_libraries:
      'Q:\Multimedia\TV': TV Shows

    exclusions:
    - tag: customcards
  
  - file: ./yaml/sonarr_sync_tv.yml
    volumes:
      /share/Multimedia/TV: 'Q:/Multimedia/TV'
    add_template: tv_template
    

tmdb:
  api_key: [[key]]
```

### Series YAML

```yaml
templates:
  tv_template:
    card_type: Beedman/GradientLogoTitleCard
    extras:
      logo: './source/Mr. Mercedes (2017)/logo.png'
libraries:
  TV Shows:
    path: Q:\Multimedia\TV
series:
  Mr. Mercedes (2017):
    template: tv_template
    media_directory: 'Q:\Multimedia\TV\Mr. Mercedes'
    year: '2017'
    title: Mr. Mercedes
```

### Debug Log

[DEBUG] [22-08-22 10:16:02] Command: magick composite -gravity southwest -geometry +50+50 "I:\Portable Apps\TitleCardMaker\modules\.objects\series_count_text.png" "I:\Portable Apps\TitleCardMaker\modules\.objects\gradient_title.png" "\\192.168.68.109\QNAP\Multimedia\TV\Mr. Mercedes\Season 1\Mr. Mercedes (2017) - S01E01.jpg"  stdout: b''  stderr: b"composite: unable to open image '\\192.168.68.109\\QNAP\\Multimedia\\TV\\Mr. Mercedes\\Season 1\\Mr. Mercedes (2017) - S01E01.jpg': No such file or directory @ error/blob.c/OpenBlob/3537.\r\n"
