### ISSUE TITLE
Optionally skip localized images 

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#250]
Some episodes on TMDb have localized images that have text on them - such as [this](https://www.themoviedb.org/tv/1911-bones/season/11/episode/10/images/backdrops?image_language=en) episode of Bones where a TCM user uploaded a standard card for the episode.

TCM doesn't care about the language setting of an image for source image selection, but this should be toggle-able globally like so:
```yaml
# prefences.yml file
tmdb:
  skip_localized_images: true | [false]
```
And per-series like so:
```yaml
series:
  Breaking Bad (2008):
    tmdb_skip_localized_images: true | false # Defaults to global value
```
