### ISSUE TITLE
Clarify sync `volumes` and `plex_libraries` specification

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#251]
The specification of the volumes and paths sacrifices clarity and intuition for brevity. Ideally these options would be more new-user-friendly. Possibly change specification to:

```yaml
sonarr:
  sync:
    volumes:
    - sonarr_path: /sonarr/path1/
      tcm_path: /tcm/path1/
    - sonarr_path: /sonarr/path2/
      tcm_path: /tcm/path2/
    plex_libraries:
    - library: TV
      path: /media/tv/
    - library: Anime
      path: /media/anime/
```

Not 100% sold on changing the specification to this (obviously it will break previous sync setups), but I do think the specification is not very clear.
