### ISSUE TITLE
BUG - Clean malformatted title

### ISSUE THREAD

**Issue by JakobTischler** [CollinHeist/TitleCardMaker#253]
### Installation

GitHub - master branch

### Describe the Bug

Using TMDB, I got an episode title `"\tMany Mickles Make a Muckle"`. Not sure why there'd be a tab in there, but it leads to the error:
`OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: "media\\TV\\TURN - Washington's Spies (2014)\\Season 3\\TURN - Washington's Spies (2014) - S03E06 - \tMany Mickles Make a Muckle.jpg"`

### Expected Behavior

I think the title should be cleaned in terms of replacing line feeds, carriage returns, tabs etc. with spaces and additionally then trimming it. At the latest, the file path should be validated/cleaned.

### Steps to reproduce the behavior

1. Run "TURN: Washington's Spies"
2. Wait for S03E06

### Series YAML

```yaml
"TURN: Washington's Spies":
        year: 2014
        library: TV
        font:
            file: ./fonts/TrajanPro-Bold.otf
            stroke_width: 20%
            size: 120%
```

### Debug Log

(Not sure who to add the file here)
