### ISSUE TITLE
Allow for library-wide card type specification

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#26]
Currently any non-standard card type has to be specified per-show, but for library styles (like the `AnimeCard`), this is repetitive and tedious.

Changing the series yaml file to some variation of:

```yaml
libraries:
  TV Shows:
    path: /media/tv/
    card_type: standard # Default
  Anime:
    path: /media/anime/
    card_type: anime
```

Would allow for all shows of a specified library to automatically have that assigned card, and then the card type for a series can always be overwritten by manually specifying the `card_type` key for the series.
