### ISSUE TITLE
Modify `episode_ranges` to accept ranges like `s{season}e{episode}`

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#264]
The custom season title/source image specification via `episode_ranges` should take indices like `s{season}e{episode}` - e.g. `s2e1`.

This enable episode-specific overrides for series without absolute ordering (i.e. non-Anime).

Ranges would only be allowed within a season, because TCM has no way of knowing how long to extend the range by if multi-season.

---

Example of this:
```yaml
series:
  Mr. Robot (2015):
    episode_ranges:
      s1e1-s1e5: First Five Episodes
      # etc.
```
