### ISSUE TITLE
Optionally filter Sonarr sync by downloaded series only

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#267]
Option to filter out series that aren't downloaded should be added to Sonarr sync, like so:
```yaml
sonarr:
  # ...
  sync:
    file: ./yaml/sonarr_sync.yaml
    downloaded_only: true # Defaults to false
```

The Sonarr `/series` API endpoint returns the `sizeOnDisk` attribute, which is probably the best thing to use. Just filter out those whose `sizeOnDisk` value is 0 (if this is enabled).
