### ISSUE TITLE
(Optionally) remake cards if a new title is released

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#272]
Particularly when sourcing episode data from Sonarr/TVDb, the titles for unreleased episodes are incorrect and then later corrected. In these instances the datafile and cards have to be manually corrected.

TCM should check for title changes against the data source and updated titles should delete the old cards.

This should be toggle-able so that people can enter manual titles and those are not overwritten. The toggle for this should be per-series `refresh_titles`, e.g.:

```yaml
series:
  Pantheon (2022):
    refresh_titles: false # Default to true
```
