### ISSUE TITLE
Set season titles in Plex

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#291]
There should be an option to match the season titles in Plex and those specified via `seasons`. Probably a global `plex` option `match_season_titles`, like so:

```yaml
plex:
  # options
  match_season_titles: true
```

Which would only apply for season titles like so:
```yaml
seasons:
  1: Part I
  2: Part II
  # etc.
```

This obviously couldn't work for `episode_ranges`, and should only take effect for non-default season titles
