### ISSUE TITLE
Add support for Emby

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#297]
Came across the Emby API the other day, shouldn't be too difficult to implement the barebones of title card uploading to an Emby server. Not a high priority IMO

API: http://swagger.emby.media/?staticview=true#/ImageService/postItemsByIdImagesByType

**Comment by CollinHeist** [comment]
If TCM needs to handle multiple types of media servers, then the `library` attribute will need to be modified to handle the user specifying both a Plex and Emby (or Jellyfin) server at the same time, and potentially with the same library names. 

---

The best solution I can think of would be to modify the `libraries` section of a series YAML file, like so:
```yaml
libraries:
  TV Show:
    path: # path
    media_server: plex | emby | jellyfin
```

The `media_server` attribute would be required only if `plex` and `emby` and `jellyfin` are all specified.

---

The `plex_name` attribute should also be renamed to `library_name`

**Comment by CollinHeist** [comment]
Preferences for Emby should be as follows:
```yaml
emby:
  url: # bla bla
  api_key: # beep boop
  sync:
  - mode: append
    compact_mode: true
    card_directory: ./cards/
    volumes: {} # etc
    exclusions: {} # etc.
  - file: ./emby_sync.yaml
    add_template: template_name
    libraries:
    - Library Name
```
Sync options are practically identical to Plex
