### ISSUE TITLE
Allow background images in `LogoTitleCard`

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#325]
Suggested on the Discord, the `LogoTitleCard` should support background images, ideally with optional blurring.

Example:
<img src="https://user-images.githubusercontent.com/17693271/231314304-ede301ef-60e2-4e8c-962e-029c1ed9cf48.png" width="600"/>

To be backwards compatible, the background image will have to be manually enabled via extra. In addition, blurring should blur the logo by default (also for backwards compatibility), so which "layer" is blurred should also be adjusted via extra. Possibly

```yaml
extras:
  use_background_image: true | false # Default false, override any background color specified
  blur_only_image: true | false # Default false, only applies if blur modifier or extra is provided
```
