### ISSUE TITLE
Cards being made but are not updating in Plex

### ISSUE THREAD

**Issue by miltownsho** [CollinHeist/TitleCardMaker#334]
So I have tried on and off for two weeks trying to get this to work.  I have changed settings, read and re-read the WIKI.  There has to be something simple that I am missing.

The cards are made but they are never actually updated into Plex.

Is someone able to maybe tell me what I have set wrong?

options:
  source: ./source/
  series:
  - ./yaml/sonarr_sync.yml
  filename_format: "{full_name} - S{season:02}E{episode:02}"
  season_folder_format: "Season {season:02}"
  sync_specials: false
  
plex:
  url: http://192.168.1.37:32400/         # Your local Plex IP address
  token: XXXXXXXXXXXXXXXX             # Your Plex token
  integrate_with_pmm_overlays: true

sonarr:
  url: http://localhost:38082/api/v3               # Your Sonarr IP address
  api_key: XXXXXXXXXXXXXXXXXX        # Your Sonarr API key
  sync:
  - card_directory: ./config/cards/
    downloaded_only: true
    monitored_only: true
    plex_libraries: # YOUR LIBRARY PATHS
      S:/TV: TV
  - file: ./config/sonarr_sync_tv.yml
    series_type: standard

tmdb:
  api_key: XXXXXXXXXXXXXXXX       # Your TMDb API key here

I just realized I do have sonarr v4 now, so I don't know if the URL needs to be changed, but it connects just fine and this problem existed before I upgraded.

**Comment by CollinHeist** [comment]
If possible, could you reformat what you posted in a code block like so?

<img width="115" alt="Screenshot 2023-04-22 at 1 06 58 PM" src="https://user-images.githubusercontent.com/17693271/233802178-f844c776-4349-410b-ad12-b566b2e50231.png">

That is using the ` character. I only ask because you could have a pretty basic YAML formatting problem, but I can't tell with how it is currently.

Also, can you post a snippet of your YAML sync file? At least the libraries and 1-3 series

**Comment by miltownsho** [comment]
```yaml
options:
source: ./source/
series:

./yaml/sonarr_sync.yml
filename_format: "{full_name} - S{season:02}E{episode:02}"
season_folder_format: "Season {season:02}"
sync_specials: false
plex:
url: http://192.168.1.37:32400/ # Your local Plex IP address
token: XXXXXXXXXXXXXXXX # Your Plex token
integrate_with_pmm_overlays: true

sonarr:
url: http://localhost:38082/api/v3 # Your Sonarr IP address
api_key: XXXXXXXXXXXXXXXXXX # Your Sonarr API key
sync:

card_directory: ./config/cards/
downloaded_only: true
monitored_only: true
plex_libraries: # YOUR LIBRARY PATHS
S:/TV: TV
file: ./config/sonarr_sync_tv.yml
series_type: standard
tmdb:
api_key: XXXXXXXXXXXXXXXX # Your TMDb API key here
```

**Comment by miltownsho** [comment]
libraries:
  TV:
    path: C:\Users\jason\Documents\TitleCardMaker\config\cards
series:
  11.22.63 (2016): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\11.22.63 (2016)'}
  12 Monkeys (2015): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\12 Monkeys (2015)'}
  12 oz. Mouse (2005): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\12 oz. Mouse (2005)'}
  1883 (2021): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\1883'}
  19-2 (2014): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\19-2 (2014)'}
  1923 (2022): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\1923'}

**Comment by CollinHeist** [comment]
@miltownsho So I still can't tell if you have formatting problems, when you are pasting YAML the spacing needs to be **exactly** correct. The way you have it shown in your comments is wrong, but I'll assume that it is just incorrectly copy/pasted.

The problem is the series in your sync file do not have a `library` assigned to them. What paths are your libraries under in Sonarr? You show the only library as `S:/TV`, is that correct? Look in your Sonarr under `Settings` > `Media Management` > `Root Folders`. If the only library path is actually `S:/TV` (which probably should be `S:\\TV` since you are on Windows), then delete the sync file and re-sync to see if TCM correctly assigns the libraries.

**Comment by miltownsho** [comment]
I did verify that is the root folder.  
![root](https://user-images.githubusercontent.com/128551630/233809381-426fb186-041f-4475-bd73-b45531844ca3.PNG)

I went into the YAML folder and deleted the sync file after changing from S:/TV to S:\\TV as you stated in in the preferences and now I get this error when I attempt to run the program.  
![Error](https://user-images.githubusercontent.com/128551630/233809970-fd57cb2a-e5fc-4d97-9a3d-2c683949113d.PNG)

I am going to attempt to repost the YAML correctly right now as well for you.  Thanks again for helping!

**Comment by miltownsho** [comment]
```yaml
options:
  source: ./source/
  series:
  - ./yaml/sonarr_sync.yml
  filename_format: "{full_name} - S{season:02}E{episode:02}"
  season_folder_format: "Season {season:02}"
  sync_specials: false
  
plex:
  url: http://192.168.1.37:32400/         # Your local Plex IP address
  token: iLhZWRySr5H9XTFbPzVQ             # Your Plex token
  integrate_with_pmm_overlays: true

sonarr:
  url: http://localhost:38082/api/v3               # Your Sonarr IP address
  api_key: 6adbf54299514f1cbcfb6f09db203ce5        # Your Sonarr API key
  sync:
  - card_directory: ./config/cards/
    downloaded_only: true
    monitored_only: true
    plex_libraries: # YOUR LIBRARY PATHS
      S:\\TV: TV
  - file: ./config/sonarr_sync_tv.yml
    series_type: standard

tmdb:
  api_key: 533b2893b19707f30dffb0e1c78936ed        # Your TMDb API key here
```

**Comment by CollinHeist** [comment]
> I did verify that is the root folder.

Okay this part looks good then. After syncing, what's your YAML look like?

---

As for the error, it looks like you are syncing to the file `./config/sonarr_sync_tv.yml`, with this line of your `sync`:
```yaml
file: ./config/sonarr_sync_tv.yml
```
But you are reading the file `./yaml/sonarr_sync.yml` with this line of your `options`:
```yaml
series:
- ./yaml/sonarr_sync.yml
```
You want these two to match, so that you sync (write) to the same file you then read.

**Comment by miltownsho** [comment]
I am also confused as to why it states in the preferences the card directory should be titlemaker/config/cards but all the cards are being thrown into titlemaker/cards.  Thank you for editing out the api keys!

**Comment by CollinHeist** [comment]
Most likely there were some entries in the Sync file (perhaps from an old sync) which had the card directory as `./cards/`. Whenever you change a Sync setting TCM will not edit any previously made entries/files, so you have to delete/remake it.

**Comment by miltownsho** [comment]
Okay, so I changed both lines to be ./config/sonarr_sync.tv.yml and the program runs again!  YAY

But, it has now already completed two series and I am not seeing a change when I load up Plex, I did refresh the metadata but no dice.  

The new cards are now going into the config/cards file.  These don't have to go into the series subfolders?  I swear I read it did not have to, but that's all my brain can come up with as to why Plex still does not see the newly created cards

**Comment by miltownsho** [comment]
I did a sponsorship because I truly appreciate your help as well

**Comment by CollinHeist** [comment]
> Okay, so I changed both lines to be ./config/sonarr_sync.tv.yml and the program runs again! YAY

Nice! Okay that's the first step, haha.

> But, it has now already completed two series and I am not seeing a change when I load up Plex, I did refresh the metadata but no dice.

So the most important thing to note is that TCM __requires__ a series to have a `library` value for it to load the cards within Plex. Can you post a snippet of your Sync file so we can check if that's present? If not, there are a couple fixes we can try.

> The new cards are now going into the config/cards file. These don't have to go into the series subfolders?

No it does not, TCM can put the cards anywhere and then it will load the cards directly into Plex via the API - this is preferable so that your card filenames don't have to exactly match the Plex video file names (which is required for local assets), and it prevents Sonarr from deleting them everytime you import a new episode.

> I did a sponsorship because I truly appreciate your help as well

Thank you so much! I appreciate it a ton🙌

**Comment by miltownsho** [comment]
libraries:
  TV:
    path: C:\Users\jason\Documents\TitleCardMaker\config\cards
series:
  11.22.63 (2016): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\11.22.63 (2016)'}
  12 Monkeys (2015): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\12 Monkeys (2015)'}
  12 oz. Mouse (2005): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\12 oz. Mouse (2005)'}
  1883 (2021): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\1883'}
  19-2 (2014): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\19-2 (2014)'}
  1923 (2022): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\1923'}
  24 (2001): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\24'}
  8 Simple Rules (2002): {media_directory: 'C:\Users\jason\Documents\TitleCardMaker\config\cards\8 Simple Rules (2002)'}

This is now from the config folder since the YAML is now blank as we changed the preference

**Comment by CollinHeist** [comment]
Okay so none of those have a `library` assigned, which is why nothing is being loaded in Plex.

Setting the `plex_libraries` sync option is what controls this part of TCM, but it might be easier to just not bother with that since you have only one library. We'll do something different.

1. Add `add_template: tv-library` to your sync settings, like so:
```yaml
  sync:
  - card_directory: ./config/cards/
    downloaded_only: true
    monitored_only: true
    add_template: tv-library
  - file: ./config/sonarr_sync_tv.yml
    series_type: standard
```
2. Create a `tv-template` template in your sync file - the top should look like this:
```yaml
libraries:
  TV:
    path: C:\Users\jason\Documents\TitleCardMaker\config\cards
templates:
  tv-template:
    library: TV
series:
# ...
```
3. Delete all the series that TCM just added to the sync file (so they are remade) - your entire sync file should look like this:
```yaml
libraries:
  TV:
    path: C:\Users\jason\Documents\TitleCardMaker\config\cards
templates:
  tv-template:
    library: TV
series: {}
```

Re-sync and then paste the results here

**Comment by CollinHeist** [comment]
For context, what this does is tells TCM to add the `tv-template` Template to all series it Syncs from Sonarr; we are then adding the `TV` library to that Template so that any series using it is assigned to the `TV` library, and TCM will then load it's cards into Plex

**Comment by miltownsho** [comment]
![skip](https://user-images.githubusercontent.com/128551630/233811114-5f2d69e3-12f4-4dd5-80b4-5c7d62d67b12.PNG)

**Comment by miltownsho** [comment]
I doubled checked what you told me to edit and made sure it was correct.  At first I did not delete plex libraries then tried again, same result.

**Comment by CollinHeist** [comment]
That's my bad, I accidentally typed out two different names. Change the name of the template to `tv-library` from `tv-template`, so that section should be:
```yaml
templates:
  tv-library:
    library: TV
```

**Comment by miltownsho** [comment]
Okay its running, but at the start it shows "Read 15 Shows" and skips the ones that it had previously made cards for (even though I deleted them and cleared the sync log.)  So it starts at Better Call Saul for example.

It also made cards for Seasons I do not have (I only have Season 6 of Better Call Saul, yet it made title cards for every season.)

Still did not appear in Plex unfortunately and now getting an error of Library "TV" was not found in Plex

**Comment by CollinHeist** [comment]
> and skips the ones that it had previously made cards for (even though I deleted them and cleared the sync log.)

That's expected unless you change the card config in some way.

> It also made cards for Seasons I do not have (I only have Season 6 of Better Call Saul, yet it made title cards for every season.)

This is also expected. It is pulling episode data from Sonarr, which has episodes you do not have on Plex. You can change this with the [episode data source](https://github.com/CollinHeist/TitleCardMaker/wiki/Options-Attributes#episode-data-source) option by setting it to `plex`.

> Still did not appear in Plex unfortunately and now getting an error of Library "TV" was not found in Plex

Is your Plex library not named `TV`?

**Comment by miltownsho** [comment]
I have two Plex libraries, one named TV Shows and one named Movies, each has a separate folder on my S: drive.  I went and changed the name of the TV library in the sync file to TV Shows and attempted to run again and it threw a bunch of errors.

One I get this running is there a simple way to change something in the card config so it can remake all cards?  I deleted the old ones so it obviously would be missing some.

I originally went with Sonarr since the WIKI stated it was much faster, but if it creates the extra cards even though I do no have those episodes downloaded, I may be better off changing to use Plex instead as when I deleted the first batch of cards it was 8 GIGs on its own.

I feel so stupid, like this shouldn't be that difficult, thank you again, sorry it's taking up so much of your time.  If I can just get it to sync I can probably figure out the rest cause push comes to shove I will keep the original preferences and sync files saved as backup!  HAHA

**Comment by miltownsho** [comment]
Oddly enough it did not create those extra cards until we made the recent changes

**Comment by CollinHeist** [comment]
Change your libraries section to this:
```yaml
libraries:
  TV:
    path: C:\Users\jason\Documents\TitleCardMaker\config\cards
    library_name: TV Shows
```

> One I get this running is there a simple way to change something in the card config so it can remake all cards?

Why do you want to remake the cards? If you haven't changed the config, then it will just remake them exactly as they are now.

> I originally went with Sonarr since the WIKI stated it was much faster, but if it creates the extra cards even though I do no have those episodes downloaded, I may be better off changing to use Plex instead as when I deleted the first batch of cards it was 8 GIGs on its own.

So you can _sync_ from Sonarr, that is much faster, while getting episode data from Plex - those are two separate things entirely. You might look at changing your card extension to `webp` or the card dimensions as well, if you are worried about the size the cards take up. All of these are options listed/described [here](https://github.com/CollinHeist/TitleCardMaker/wiki/Options-Attributes).

> I feel so stupid, like this shouldn't be that difficult, thank you again, sorry it's taking up so much of your time. If I can just get it to sync I can probably figure out the rest cause push comes to shove I will keep the original preferences and sync files saved as backup! HAHA

No need to apologize/feel stupid, haha. The sync stuff can be complicated to first set up
