### ISSUE TITLE
HELP - Would it be possible to automate the minimaker to add a white border around custom posters ?

### ISSUE THREAD

**Issue by TRaSH-** [CollinHeist/TitleCardMaker#349]
### Installation

Docker - master tag

### Describe your Problem

i'm using PMM and using the poster from  musikmann2000,
but he hasn't done all the movies or shows i've and sometimes i prefer a few of my own found posters.
would it be possible to setup a certain automated process like you add posters in the source folders and they get converted to the ones with the white border ?

### Screenshots

These i created manually with TitleCardMaker

![image](https://github.com/CollinHeist/TitleCardMaker/assets/6155095/9787ae86-8b13-4818-a6a0-9ee9ad925eb8)

![image](https://github.com/CollinHeist/TitleCardMaker/assets/6155095/585a9d45-c675-46d0-ac5b-ce1f53dccfc2)

### Preference File

```yaml
options:
  source: /config/source/
#  series:
#  - /config/yaml/sonarr_sync.yml
#  filename_format: "{full_name} - S{season:02}E{episode:02}"
#  season_folder_format: "Season {season:02}"
#  sync_specials: false

#plex:
#  url: http://192.168.2.200:32400/         # Your local plex IP address
#  token: xxxx         # Your Plex token
```

### Debug Log

no debug log
