### ISSUE TITLE
HELP - Update list does not exist

### ISSUE THREAD

**Issue by CappiSteijns** [CollinHeist/TitleCardMaker#372]
### Installation

Docker - master tag

### Describe your Problem

I am trying to set up the Tautulli Integration so it will automatically blur or unblur when watched or unwatched. 

I followed the steps from [here](https://github.com/CollinHeist/TitleCardMaker/wiki/Tautulli-Integration).

I'm probably doing something wrong in [step 3 ](Integrating with TitleCardMaker) and I'm not sure what it could be. 
Does it automatically make a file named "update.txt" in the same location as the update_card.sh directory, or do I need to create one myself? When I create a text document named "update" unraid automatically deletes it? 

I'm using the app template on Unraid. 

### Screenshots

![image](https://github.com/CollinHeist/TitleCardMaker/assets/84481241/c34fa4ca-2856-4b90-b85d-79c542a5b5e1)
![image](https://github.com/CollinHeist/TitleCardMaker/assets/84481241/52683e83-91a0-486c-bf4f-938a31078010)

### Preference File

```yaml
options:
  source: /config/source/
  series: /config/tv.yml
  episode_data_source: sonarr
  
plex:
  url: http://192.168.68.61:32400
  token: ####################

sonarr:
  url: http://192.168.68.61:32710/
  api_key: ##############################

tmdb:
  api_key: ###########################
  
tautulli:
  url: http://192.168.68.61:8180         # Your Tautulli URL
  api_key: #############################            # Your API key
  update_script: /tautulli/update_card.sh
  verify_ssl: true
  username: CappiSteijns
  agent_name: Update TitleCardMaker      # Your Username
  script_timeout: 0
```

### Series YAML

```yaml
libraries:
  Series HD:
    path: /media

  Anime:
    path: /Media/Anime/
    card_type: anime

series:
  Mr. Robot (2015):
    library: TV
    font:
      color: "#CE3F39"
      file: /config/fonts/MR ROBOT.ttf
    seasons:
      0: "specials_0.0"
      1: "season_1.0"
      2: "season_2.0"
      3: "season_3.0"
      4: "season_4.0"
  
  "Demon Slayer: Kimetsu no Yaiba (2019)":
    library: Anime
    translation:
      language: ja
      key: kanji
    seasons:
      1: Finding my Life's Purpose
      2: Mugen Train
      3: Entertainment District

  Based on a True Story (2023):
    library: Series HD
    card_type: tinted glass
    episode_text_format: "Chapter {abs_number}"
    watched_style: art
    unwatched_style: blur


Note that I'm still testing, this is the default YAML but I only use the last tv show : Based on a true story.
```

### Debug Log

[maker.zip](https://github.com/CollinHeist/TitleCardMaker/files/12243744/maker.zip)

**Comment by CollinHeist** [comment]
@CappiSteijns All of your setup looks correct, and I see in the logs that TCM detects the integration, and is trying to read the update file, and at 08-02-23 20:39:38.827 it _did_ read the update file, so that's a good sign.

The Tautulli agent that TCM created actually creates the `update.txt` file for you, all your template does it tell TCM what file to be expecting.

Have you watched any content to verify it works? You can test it manually like so (names might be wrong since I'm away from tautulli)
1. Go to the Notification Agent in the Tautulli UI, and then doing "Test" (can't remember what it's called) - the last tab in the agent page
2. In the script arguments, just type a number like `123` and run the test.
3. If you see that there is an `update.text` file with that number in it, then the agent is working as expected.
4. If TCM's part is working, you'll get log messages that the file was read, and it should print the numbers you typed above.

**Comment by CollinHeist** [comment]
Okay if Tautulli is not writing the file, then that's likely the root cause here. 

Let's confirm the script is executable - go to where the `update_card.sh` file is, and type:
```bash
./update_card.sh 123
```
An `update.txt` file should be created with `123` inside.

Then we can confirm TCM sees that file - the logs should say it has read the file and then an error (because the 123 doesn't correspond to an actual Episode).

---

When you run the agent, do your Tautulli logs show anything? It should say whether the script executed successfully.

**Comment by CappiSteijns** [comment]
> Let's confirm the script is executable - go to where the `update_card.sh` file is, and type:
> 
> ```shell
> ./update_card.sh 123
> ```
Okey, so I tried to execute the script but I get the following:
`bash: ./update_card.sh: cannot execute: required file not found`.
I redid the `chmod +x .` command but nothing changes. When I changed the ownership of the file to another user I got the following message:
`bash: ./update_card.sh: Permission denied` so it sounds like it does find the file?

![image](https://github.com/CollinHeist/TitleCardMaker/assets/84481241/8b055ddc-d040-40b1-b89d-9f92dc25f185)

> When you run the agent, do your Tautulli logs show anything? It should say whether the script executed successfully.

AH, Geuss this could be a good reason why it doesn't work.
`2023-08-02 23:56:51 - DEBUG :: CP Server Thread-13 : Sending test Script notification.
2023-08-02 23:56:51 - DEBUG :: CP Server Thread-13 : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'test' (manual trigger).
2023-08-02 23:56:51 - INFO :: Thread-3 (process_queue) : Tautulli NotificationHandler :: Preparing notification for notifier_id 32.
2023-08-02 23:56:51 - DEBUG :: Thread-3 (process_queue) : Tautulli Notifiers :: Trying to run notify script: /config/update_card.sh, arguments: ['123'], action: test
2023-08-02 23:56:51 - DEBUG :: Thread-3 (process_queue) : Tautulli Notifiers :: Full script is: ['/config/update_card.sh', '123']
2023-08-02 23:56:51 - DEBUG :: Thread-3 (process_queue) : Tautulli Notifiers :: Executing script in a new thread.
2023-08-02 23:56:51 - ERROR :: Thread-804 (run_script) : Tautulli Notifiers :: Failed to run script: [Errno 2] No such file or directory: '/config/update_card.sh'`

Just to clarify things for myself regarding the update_card.sh file and the creation of:

I open up Notepad++ and create a new file, I insert `#!/bin/sh
echo "$@" >> update.txt` and save it as `normal text file` with the name `update_card.sh`.
Or should I save it as `Unix Script file` instead of `normal text file`? Anyhow I tried both of them but still get the same errors.

**Comment by CollinHeist** [comment]
> Okey, so I tried to execute the script but I get the following: bash: ./update_card.sh: cannot execute: required file not found

So a quick [search](https://unix.stackexchange.com/questions/721844/linux-bash-shell-script-error-cannot-execute-required-file-not-found) shows this could be some issue with you writing the file in Windows, and then saving it on Linux. I would rewrite it either not through Windows (perhaps your Unraid terminal), or otherwise remove the Windows line characters from the file.

> I redid the chmod +x . command but nothing changes.

This needs to be `chmod +x ./update_card.sh`, just in case you weren't trying that.

> bash: ./update_card.sh: Permission denied

So I don't know your specific permission structure, but you need to make sure the update_card.sh file is accessible by the User/Group of Tautulli, if not all users. You can use the `chown` for this.

> I open up Notepad++ and create a new file, I insert #!/bin/sh echo "$@" >> update.txt and save it as normal text file with the name update_card.sh.
Or should I save it as Unix Script file instead of normal text file?

So I don't use Notepad++, but you need to make sure the file is exactly named `update_card.sh` (or whatever appears in your notification agent) - it cannot be `update_card.sh.txt`, or anything like that. Given that the Tautulli logs show that file as not existing, that's worth double checking.

**Comment by CappiSteijns** [comment]
> > Okey, so I tried to execute the script but I get the following: bash: ./update_card.sh: cannot execute: required file not found
> 
> So a quick [search](https://unix.stackexchange.com/questions/721844/linux-bash-shell-script-error-cannot-execute-required-file-not-found) shows this could be some issue with you writing the file in Windows, and then saving it on Linux. I would rewrite it either not through Windows (perhaps your Unraid terminal), or otherwise remove the Windows line characters from the file.

Whoe! That did something! :) I created the file using the Unraid terminal and now Tautulli can find and use the .sh script!

(Just for my documentation and maybe for someone else)
Open terminal and navigate to: `/.../appdata/tautulli/`
Create a file: `nano update_card.sh` now you can fill in the script. `Ctrl + O` to save and `Ctrl + X` to exit nano.
last step: `chmod +x update_card.sh`

Now when I test the notification agent it finds the file, creates the `update.txt` file with the script argument.
```
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli NotificationHandler :: Notifiers enabled for notify_action 'on_watched'.
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli NotificationHandler :: Checking global notification conditions.
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli NotificationHandler :: Global notification conditions evaluated to 'True'.
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli Helpers :: Image 'Based on a True Story - Season 1' (poster) transformed on Cloudinary.
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli NotificationHandler :: Checking custom notification conditions for notifier_id 32.
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli NotificationHandler :: {1} username | is | 'Ca********s' > 'Ca********s' > True
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli NotificationHandler :: {2} media_type | is | 'episode' > 'episode' > True
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli NotificationHandler :: Condition logic [blank]: {1} and {2} > True
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli NotificationHandler :: Custom conditions evaluated to 'True'. Conditions: [True, True].
2023-08-03 09:16:20 - INFO :: Thread-3 (process_queue) : Tautulli NotificationHandler :: Preparing notification for notifier_id 32.
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli Notifiers :: Trying to run notify script: /config/update_card.sh, arguments: ['39275'], action: watched
2023-08-03 09:16:20 - DEBUG :: Thread-3 (process_queue) : Tautulli Notifiers :: Full script is: ['/config/update_card.sh', '39275']
> 
```
> > I redid the chmod +x . command but nothing changes.
> 
> This needs to be `chmod +x ./update_card.sh`, just in case you weren't trying that.

Sorry should've copy pasted the whole command.
> > bash: ./update_card.sh: Permission denied
> 
> So I don't know your specific permission structure, but you need to make sure the update_card.sh file is accessible by the User/Group of Tautulli, if not all users. You can use the `chown` for this.
> 
> > I open up Notepad++ and create a new file, I insert #!/bin/sh echo "$@" >> update.txt and save it as normal text file with the name update_card.sh.
> > Or should I save it as Unix Script file instead of normal text file?
> 
> So I don't use Notepad++, but you need to make sure the file is exactly named `update_card.sh` (or whatever appears in your notification agent) - it cannot be `update_card.sh.txt`, or anything like that. Given that the Tautulli logs show that file as not existing, that's worth double checking.

The only problem left is that I still get the ```[DEBUG] [08-03-23 09:16:22.062] Update list does not exist``` within the TitleCardMaker logs so it still doesn't change anything when an episode has been watched... :/

**Comment by CappiSteijns** [comment]
Found something in the log: `[ERROR] [08-03-23 09:26:50.441] Error reading update list, skipping and deleting`

[maker.zip](https://github.com/CollinHeist/TitleCardMaker/files/12248047/maker.zip)

**Comment by CollinHeist** [comment]
@CappiSteijns Glad we got that figured out - Windows is the bane of my existence, haha. I wouldn't have expected the different line-ending characters to be a problem.

> Found something in the log: [ERROR] [08-03-23 09:26:50.441] Error reading update list, skipping and deleting

I wouldn't worry about that, maybe you/Tautulli wrote some bad data in the file and TCM couldn't read it. Later on there is this:
```
[DEBUG] [08-03-23 09:27:53.454] Read update list ({39270})
[DEBUG] [08-03-23 09:27:53.901] Rating key 39270 -> 1 item(s)
```
Which means TCM is reading the file, so I believe it's working.

**Comment by CappiSteijns** [comment]
Okey so I'm setting up the Tautulli integration because I want to do the following:
https://user-images.githubusercontent.com/17693271/185819730-a2c55a3a-63cc-4f0e-8061-891edd8d64d0.gif

But can't seem to get it working. It only blurs or unblurs when I restart the container. 

So right now it does make the update.txt file:
![image](https://github.com/CollinHeist/TitleCardMaker/assets/84481241/78532344-0857-4070-a249-7ae2d8bff503)

But i'm geussing it won't get picked up by TitleCardMaker unless, as I said before, I restart the docker container. 

I'm must be doing something wrong but I',m not sure what yet.

```
options:
  source: /config/source/
  series: /config/tv.yml
  episode_data_source: sonarr
  
plex:
  url: http://192.168.68.61:32400
  token: nyJoGF4EzdY8m3yL9K9G

sonarr:
  url: http://192.168.68.61:32710/
  api_key: 68060849711a43fb84e3a0ff33ff4649

tmdb:
  api_key: 27250c25bf7a970f7e5184cceadc6c8b
  
tautulli:
  url: http://192.168.68.61:8180         # Your Tautulli URL
  api_key: 2cc6eb879f424a599af34f64d08bcd74            # Your API key
  update_script: /tautulli/update_card.sh
  verify_ssl: true
  username: CappiSteijns
  agent_name: Update TitleCardMaker      # Your Username
  script_timeout: 0
```
```
libraries:
  Series HD:
    path: /media
    
  Anime:
    path: /Media/Anime/
    card_type: anime
    
series:
  Mr. Robot (2015):
    library: TV
    font:
      color: '#CE3F39'
      file: /config/fonts/MR ROBOT.ttf
    seasons:
      0: specials_0.0
      1: season_1.0
      2: season_2.0
      3: season_3.0
      4: season_4.0
      
  'Demon Slayer: Kimetsu no Yaiba (2019)':
    library: Anime
    translation:
      language: ja
      key: kanji
    seasons:
      1: Finding my Life's Purpose
      2: Mugen Train
      3: Entertainment District
      
  Based on a True Story (2023):
    library: Series HD
    card_type: tinted glass
    episode_text_format: Chapter {abs_number}
    watched_style: unique
    unwatched_style: art
    
  My Adventures with Superman (2023):
    library: Series HD
    card_type: tinted glass
    episode_text_format: Chapter {abs_number}
    watched_style: unique
    unwatched_style: art
```
![image](https://github.com/CollinHeist/TitleCardMaker/assets/84481241/41f5a136-ed8a-4ff5-a7c6-5a4a598938a6)
![image](https://github.com/CollinHeist/TitleCardMaker/assets/84481241/8b2ed22a-7395-49ef-8d18-9befee59243a)
