### ISSUE TITLE
HELP - Jellyfin sync setup and general questions

### ISSUE THREAD

**Issue by JPsychotic** [CollinHeist/TitleCardMaker#381]
### Installation

GitHub - master branch

### Describe your Problem

Hello. I tried setting it up locally and got it up so that the mini maker works. Now I tried syncing series from my jellyfin server. I specified the jellyfin options in the preferences.yml file and it did create a syn_series.yml file. Now I tried to execute the maker but it could not load the images from jellyfin.

I've got two general questions regarding the functionality of TitleCardMaker with jellyfin:
- Is it possible that the card images can be loaded from jellyfin via the API?
- Is it possible to sync the created cards to jellyfin via the API?
I know both is possible because I tried it in postman. I don't know if my setup is not correct or if it isn't possible at all. I am not storing the series or episode images in the directory where the actual video file is stored because the video files are stored on a NAS with HDDs which would be kinda slow when loading the images in jellyfin.

Thank you very much in advance!

### Preference File

```yaml
options:
  source: ./source/
  series:
  - ./config/sync_series.yml
  card_type: frame
  card_extension: jpg
  card_dimensions: 1920x1080
  validate_fonts: true
  sync_specials: false
  episode_data_source: jellyfin
  image_source_priority: jellyfin
  language_codes:
  - de
jellyfin:
  url: https://jellyfin.local/
  api_key: random_api_key
  username: Jeremy
  verify_ssl: false
  watched_style: unique
  unwatched_style: unique
  sync:
  - sync_mode: match
  - card_directory: ./config/cards
  - file: ./config/sync_series.yml
    libraries:
    - Serien
```

### Series YAML

```yaml
libraries:
  Serien:
    media_server: jellyfin
    path: D:\SourceCode\TitleCardMaker\config\cards
    library_name: Serien
series:
  'Demon Slayer: Kimetsu no Yaiba (2019)': {library: Serien, media_directory: D:\SourceCode\TitleCardMaker\config\cards\Demon Slayer - Kimetsu no Yaiba, card_type: anime, library: Serien}
```

### Debug Log

No log needed.
