### ISSUE TITLE
BUG - Jellyfin: Series "..." was not found under library "..." in Jellyfin

### ISSUE THREAD

**Issue by JPsychotic** [CollinHeist/TitleCardMaker#385]
### Installation

GitHub - develop branch

### Describe the Bug

I have sync activated and it's reading all series correctly from the jellyfin library. But when creating cards the TCM states for two series that he did not find them under their corresponding library. It only happens for two series :(

### Expected Behavior

TCM should find the series when creating cards. He does find them when he is syncing.

### Steps to reproduce the behavior

1. 
2.
...

### Preference File

```yaml
options:
  source: ./source/
  series:
  - ./config/sync_series.yml
  card_type: standard
  card_extension: png
  card_dimensions: 1920x1080
  validate_fonts: true
  sync_specials: false
  episode_data_source: jellyfin
  image_source_priority: jellyfin
  language_codes:
  - de
  - en
jellyfin:
  url: https://jellyfin.local/
  api_key: api_key
  username: Jeremy
  verify_ssl: false
  watched_style: unique
  unwatched_style: unique
  sync:
  - sync_mode: append
  - card_directory: ./config/cards
  - file: ./config/sync_series.yml
  libraries:
  - Serien
```

### Series YAML

```yaml
libraries:
  Serien:
    media_server: jellyfin
    path: .\config\cards\tvshows
series:
  Marvel's What If…? (2021): {library: Serien, media_directory: .\config\cards\tvshows\What If}
  'Mushoku Tensei: Jobless Reincarnation (2021)': {library: Serien, media_directory: .\config\cards\tvshows\Mushoku Tensei Jobless Reincarnation, card_type: anime, extras: {kanji: 無職転生 〜異世界行ったら本気だす, require_kanji: true}}
```

### Debug Log

[DEBUG] [08-19-23 17:13:47.712] Runtime arguments  :
[DEBUG] [08-19-23 17:13:47.712]        preferences : D:\SourceCode\TitleCardMaker\preferences.yml
[DEBUG] [08-19-23 17:13:47.712]                run : True
[DEBUG] [08-19-23 17:13:47.712]               sync : False
[DEBUG] [08-19-23 17:13:47.712]          frequency : {'interval': 12, 'unit': 'hours'}
[DEBUG] [08-19-23 17:13:47.712]            missing : D:\SourceCode\TitleCardMaker\missing.yml
[DEBUG] [08-19-23 17:13:47.712]                log : INFO
[DEBUG] [08-19-23 17:13:47.712]           no_color : False
[DEBUG] [08-19-23 17:13:47.712] tautulli_frequency : {'interval': 4, 'unit': 'minutes'}
[INFO] [08-19-23 17:13:47.714] Read preference file "D:\SourceCode\TitleCardMaker\preferences.yml"
[DEBUG] [08-19-23 17:13:47.759] Using "magick " ImageMagick command prefix
[INFO] [08-19-23 17:13:47.766] Read 44 show records
[INFO] [08-19-23 17:13:47.766] Starting TitleCardMaker (v1.14.2-develop37)
[INFO] [08-19-23 17:13:47.831] New version of TitleCardMaker (v1.14.2) available
[INFO] [08-19-23 17:13:47.832] Get the latest version with "git pull origin"
[INFO] [08-19-23 17:13:47.835] Read preference file "D:\SourceCode\TitleCardMaker\preferences.yml"
[DEBUG] [08-19-23 17:13:47.863] Using "magick " ImageMagick command prefix
[DEBUG] [08-19-23 17:13:47.868] Reset PersistentDatabase[remote_assets.json]
[DEBUG] [08-19-23 17:13:47.869] Not verifying SSL connections for Jellyfin
[INFO] [08-19-23 17:13:47.924] Starting to sync to series YAML files..
[INFO] [08-19-23 17:13:48.001] Synced D:\SourceCode\TitleCardMaker\config\sync_series.yml from Jellyfin
[INFO] [08-19-23 17:13:48.003] Reading series YAML file "D:\SourceCode\TitleCardMaker\config\sync_series.yml"..
[WARNING] [08-19-23 17:13:50.143] Series "Marvel's What If…? (2021)" was not found under library "Serien" in Jellyfin
[WARNING] [08-19-23 17:13:50.147] Series not found in Jellyfin <SeriesInfo name=Marvel's What If…?, year=2021>
[INFO] [08-19-23 17:13:50.148] jellyfin has no episodes for "Marvel's What If…? (2021)"
[DEBUG] [08-19-23 17:13:50.157] Not loading "Marvel's What If…? (2021)" - not found in Jellyfin
[WARNING] [08-19-23 17:13:50.166] Series "Mushoku Tensei: Jobless Reincarnation (2021)" was not found under library "Serien" in Jellyfin
[WARNING] [08-19-23 17:13:50.169] Series not found in Jellyfin <SeriesInfo name=Mushoku Tensei: Jobless Reincarnation, year=2021>
[INFO] [08-19-23 17:13:50.170] jellyfin has no episodes for "Mushoku Tensei: Jobless Reincarnation (2021)"
[DEBUG] [08-19-23 17:13:50.180] Not loading "Mushoku Tensei: Jobless Reincarnation (2021)" - not found in Jellyfin
[INFO] [08-19-23 17:13:50.225] Reading series YAML file "D:\SourceCode\TitleCardMaker\config\sync_series.yml"..
[INFO] [08-19-23 17:13:50.458] Wrote missing assets to "D:\SourceCode\TitleCardMaker\missing.yml"
