### ISSUE TITLE
HELP - Has no year skipping

### ISSUE THREAD

**Issue by zorvok** [CollinHeist/TitleCardMaker#389]
### Installation

Docker - master tag

### Describe your Problem

not creating cards or even adding to my series.yml.  skipping everything in my anime library because it has no year.  is it an issue with how my plex metadata is?  maybe I need to not use hama agent?

### Preference File

```yaml
options:
  source: /config/source/
  series:
  - /config/series/tv.yml
  execution_mode: serial
  episode_data_source: plex
  image_source_priority: tmdb, plex
  filename_format: "{full_name} - S{season:02}E{episode:02}"
  season_folder_format: "Season {season:02}"
  sync_specials: false

plex:
  url: [redacted]
  token: [redacted]
  watched_style: grayscale
  unwatched_style: unique
  integrate_with_pmm_overlays: true
  filesize_limit: 4 MB
  sync:
    mode: match
    file: /config/series/tv.yml
    compact_mode: true
    libraries:
    - TV Shows
    - Children Shows
    - Anime
    volumes:
      /data/media/: /media/

tmdb:
  api_key: [redacted]
```

### Debug Log

[DEBUG] [08-24-23 10:42:00.784] Runtime arguments  :
[DEBUG] [08-24-23 10:42:00.784]        preferences : /config/preferences.yml
[DEBUG] [08-24-23 10:42:00.784]                run : True
[DEBUG] [08-24-23 10:42:00.784]               sync : False
[DEBUG] [08-24-23 10:42:00.784]            runtime : 23:00
[DEBUG] [08-24-23 10:42:00.784]          frequency : {'interval': 24, 'unit': 'hours'}
[DEBUG] [08-24-23 10:42:00.784]            missing : /config/missing.yml
[DEBUG] [08-24-23 10:42:00.784]                log : INFO
[DEBUG] [08-24-23 10:42:00.784]           no_color : True
[DEBUG] [08-24-23 10:42:00.785] tautulli_frequency : {'interval': 4, 'unit': 'minutes'}
[INFO] [08-24-23 10:42:00.787] Read preference file "/config/preferences.yml"
[DEBUG] [08-24-23 10:42:01.261] Using "" ImageMagick command prefix
[INFO] [08-24-23 10:42:01.264] Read 730 show records
[INFO] [08-24-23 10:42:01.264] Starting TitleCardMaker (v1.14.3)
[DEBUG] [08-24-23 10:42:03.104] Latest remote version is v1.14.3
[INFO] [08-24-23 10:42:03.107] Read preference file "/config/preferences.yml"
[DEBUG] [08-24-23 10:42:03.125] Using "" ImageMagick command prefix
[DEBUG] [08-24-23 10:42:03.147] Reset PersistentDatabase[remote_assets.json]
[INFO] [08-24-23 10:42:05.523] Starting to sync to series YAML files..
[WARNING] [08-24-23 10:42:07.488] Series The Aristocrat’s Otherworldly Adventure - Serving Gods Who Go Too Far (2023) has no year - skipping
[WARNING] [08-24-23 10:42:08.903] Series BanG Dream! It's MyGO!!!!! (2023) has no year - skipping
[WARNING] [08-24-23 10:42:12.406] Series Chillin' in My 30s after Getting Fired from the Demon King's Army (2023) has no year - skipping
[WARNING] [08-24-23 10:42:17.021] Series Encouragement of Climb (2013) has no year - skipping
[WARNING] [08-24-23 10:42:18.802] Series Ghost in the Shell - Stand Alone Complex (2002) has no year - skipping
[WARNING] [08-24-23 10:42:20.777] Series Hell's Paradise (2023) has no year - skipping
[WARNING] [08-24-23 10:42:22.691] Series I'm Now Your Sister! (2023) has no year - skipping
[WARNING] [08-24-23 10:42:22.843] Series THE iDOLM@STER Cinderella Girls U149 (2023) has no year - skipping
[WARNING] [08-24-23 10:42:23.624] Series Irodorimidori has no year - skipping
[WARNING] [08-24-23 10:42:25.558] Series Kubo Won't Let Me Be Invisible (2023) has no year - skipping
[WARNING] [08-24-23 10:42:25.831] Series The Legend of Heroes - Trails of Cold Steel – Northern War (2023) has no year - skipping
[WARNING] [08-24-23 10:42:28.717] Series Mitsudomoe (2010) has no year - skipping
[WARNING] [08-24-23 10:42:30.498] Series My Life as Inukai-san's Dog (2023) has no year - skipping
[WARNING] [08-24-23 10:42:33.537] Series The Peasant Noble (2023) has no year - skipping
^C
