### ISSUE TITLE
BUG - Card Type Not Working

### ISSUE THREAD

**Issue by Speedbird757** [CollinHeist/TitleCardMaker#398]
### Installation

Docker - master tag

### Describe the Bug

When creating cards with card_type specified as star wars, the program runs but does not create the cards. In the missing.yml, it lists all the cards for each episode. Creating title cards without a card type specified works as normal. 

### Steps to reproduce the behavior

1. 
2.
...

### Screenshots

![image](https://github.com/CollinHeist/TitleCardMaker/assets/97848728/b859e0e6-652a-4547-919d-4bbfe5fa10cd)

### Preference File

```yaml
options:
  source: /Users/andrew/Documents/TitleCardMaker/source
  series: /Users/andrew/Documents/TitleCardMaker/tv.yml
  episode_data_source: tmdb
  image_source_priority: tmdb, plex
  filename_format: "{name} - S{season:02}E{episode:02} - {title}"
  
plex:
  url: 
  token: 

tmdb:
  api_key:
```

### Series YAML

```yaml
data:
  Season 1:
    1:
      title: 'Part One: Master and Apprentice'
    2:
      title: 'Part Two: Toil and Trouble'
    3:
      title: 'Part Three: Time to Fly'
    4:
      title: 'Part Four: Fallen Jedi'
    5:
      title: 'Part Five: Shadow Warrior'
    6:
      title: 'Part Six: Far, Far Away'
```

### Debug Log

[maker.log](https://github.com/CollinHeist/TitleCardMaker/files/12675629/maker.log)
