### ISSUE TITLE
BUG - Shows with character ’ aren't match on Jellyfin

### ISSUE THREAD

**Issue by foux** [CollinHeist/TitleCardMaker#415]
### Installation

Docker - master tag

### Describe the Bug

When a show has the character `’` in the name, it won't get matched in Jellyfin. The sync will work, but not assigning the cards.

For exemple, for the show `Anatomie d’un divorce (2022)` I get the following errors when running : 

```
[WARNING] [10-31-23 08:06:08.753] Series "Anatomie d’un divorce (2022)" was not found under library "Séries TV" in Jellyfin
[WARNING] [10-31-23 08:06:08.934] Series not found in Jellyfin <SeriesInfo name=Anatomie d’un divorce, year=2022, imdb_id=tt11527058, sonarr_id=0-356, tmdb_id=156401, tvdb_id=398362>
[INFO] [10-31-23 08:06:08.935] jellyfin has no episodes for "Anatomie d’un divorce (2022)"
```

Even through the series exists in Jellyfin with the sames identifiers : 
![CleanShot 2023-10-31 at 11 44 39](https://github.com/CollinHeist/TitleCardMaker/assets/246550/abdb6adc-1bc7-4326-a3e1-47924c314aca)

Just as an FYI, this series works correctly on Plex (with the same name).

It is to be noted that the character `'` works, but the character `’` doesn't.

### Expected Behavior

The series should be matched, and the cards assigned for the show

### Steps to reproduce the behavior

1.  Add a series with the character `’` in the name on Jellyfin
2. Run `main.py -r` with the series in one of the series yaml file

### Preference File

```yaml
options:
  source: /config/source/
  series: 
  - /config/yaml/jellyfin_sync.yml
  - /config/yaml/plex_sync.yml
  episode_data_source: jellyfin
  image_source_priority: tmdb, jellyfin, plex
  season_folder_format: S{season:02}
  sync_specials: true
  language_codes:
  - fr
  
plex:
  url: http://plex:32400
  token: xxx
  sync:
  - file: /config/yaml/plex_sync.yml
    mode: match
    compact_mode: false
    card_directory: /config/plex-cards
    libraries:
    - Séries TV

jellyfin:
  url: http://jellyfin:8096/
  api_key: xxx
  username: foux
  sync:
  - file: /config/yaml/jellyfin_sync.yml
    mode: match
    compact_mode: false
    card_directory: /config/cards
    libraries:
    - Séries TV

tmdb:
  api_key: xxx
  retry_count: 5
  mimimum_resolution: 800x400
  skip_localized_images: false
  logo_language_priority: fr
```

### Series YAML

```yaml
libraries:
  Séries TV:
    media_server: jellyfin
    path: /config/cards
    card_type: olivier
series:
  24 heures chrono (2001):
    library: Séries TV
    media_directory: /config/cards/24 (2001) [imdb-tt0285331]
    card_type: tinted frame
  Agent Carter (2015):
    library: Séries TV
    media_directory: /config/cards/Marvel's Agent Carter (2015) [imdb-tt3475734]
  Air Cocaïne (2023):
    library: Séries TV
    media_directory: /config/cards/Air Cocaine (2023) [imdb-]
  Alias (2001):
    library: Séries TV
    media_directory: /config/cards/Alias (2001) [imdb-tt0285333]
  American Crime Story (2016):
    library: Séries TV
    media_directory: /config/cards/American Crime Story (2016) [imdb-tt2788432]
  American Dad! (2005):
    library: Séries TV
    media_directory: /config/cards/American Dad! (2005) [imdb-tt0397306]
    card_type: comic book
    font:
      validate: true
      file: /config/fonts/44v2.ttf
  American Rust (2021):
    library: Séries TV
    media_directory: /config/cards/American Rust (2021) [imdb-tt1532495]
  Anatomie d’un divorce (2022):
    library: Séries TV
    media_directory: /config/cards/Fleishman Is in Trouble (2022) [imdb-tt11527058]
  Arcane (2021):
    library: Séries TV
    media_directory: /config/cards/Arcane (2021) [imdb-tt11126994]
  Archer (2009):
    library: Séries TV
    media_directory: /config/cards/Archer (2009) [imdb-tt1486217]
    card_type: comic book
    font:
      validate: true
      file: /config/fonts/44v2.ttf
  Arnold (2023):
    library: Séries TV
    media_directory: /config/cards/Arnold (2023) [imdb-tt27713897]
  Arrow (2012):
    library: Séries TV
    media_directory: /config/cards/Arrow (2012) [imdb-tt2193021]
  Au nom du père (2017):
    library: Séries TV
    media_directory: /config/cards/Ride Upon the Storm (2017) [imdb-tt5651032]
  Au service de la France (2015):
    library: Séries TV
    media_directory: /config/cards/A Very Secret Service (2015) [imdb-tt4367560]
  Avenue 5 (2020):
    library: Séries TV
    media_directory: /config/cards/Avenue 5 (2020) [imdb-tt10234362]
  Bad Sisters (2022):
    library: Séries TV
    media_directory: /config/cards/Bad Sisters (2022) [imdb-tt15469618]
  Battlestar Galactica (2004):
    library: Séries TV
    media_directory: /config/cards/Battlestar Galactica (2003) [imdb-tt0407362]
  'Battlestar Galactica : Blood & Chrome (2012)':
    library: Séries TV
    media_directory: /config/cards/Battlestar Galactica - Blood & Chrome (2012) [imdb-tt1704292]
  'Battlestar Galactica : Mini-série (2003)':
    library: Séries TV
    media_directory: /config/cards/Battlestar Galactica (2003) [imdb-tt0314979]
  Beau Séjour (2017):
    library: Séries TV
    media_directory: /config/cards/Beau Sejour (2017) [imdb-tt3543082]
  Beforeigners (2019):
    library: Séries TV
    media_directory: /config/cards/Beforeigners (2019) [imdb-tt8332130]
  Better Call Saul (2015):
    library: Séries TV
    media_directory: /config/cards/Better Call Saul (2015) [imdb-tt3032476]
  Big Little Lies (2017):
    library: Séries TV
    media_directory: /config/cards/Big Little Lies (2017) [imdb-tt3920596]
  Black Mirror (2011):
    library: Séries TV
    media_directory: /config/cards/Black Mirror (2011) [imdb-tt2085059]
  Blackport (2021):
    library: Séries TV
    media_directory: /config/cards/Blackport (2021) [imdb-tt14440878]
  BoJack Horseman (2014):
    library: Séries TV
    media_directory: /config/cards/BoJack Horseman (2014) [imdb-tt3398228]
    card_type: comic book
  'Borgen : Le pouvoir et la gloire (2022)':
    library: Séries TV
    media_directory: /config/cards/Borgen - Le pouvoir et la gloire [tmdb-203281]
  Borgen, une femme au pouvoir (2010):
    library: Séries TV
    media_directory: /config/cards/Borgen (2010) [imdb-tt1526318]
  Breaking Bad (2008):
    library: Séries TV
    media_directory: /config/cards/Breaking Bad (2008) [imdb-tt0903747]
  Broadchurch (2013):
    library: Séries TV
    media_directory: /config/cards/Broadchurch (2013) [imdb-tt2249364]
  Brooklyn Nine-Nine (2013):
    library: Séries TV
    media_directory: /config/cards/Brooklyn Nine-Nine (2013) [imdb-tt2467372]
  Buffy contre les vampires (1997):
    library: Séries TV
    media_directory: /config/cards/Buffy the Vampire Slayer (1997) [imdb-tt0118276]
  Calls (2017):
    library: Séries TV
    media_directory: /config/cards/Calls (FR) (2017) [imdb-tt7702924]
  Caprica (2010):
    library: Séries TV
    media_directory: /config/cards/Caprica (2010) [imdb-tt0799862]
  Chernobyl (2019):
    library: Séries TV
    media_directory: /config/cards/Chernobyl (2019) [imdb-tt7366338]
  Community (2009):
    library: Séries TV
    media_directory: /config/cards/Community (2009) [imdb-tt1439629]
  Copenhagen Cowboy (2023):
    library: Séries TV
    media_directory: /config/cards/Copenhagen Cowboy (2023) [imdb-tt16969944]
  D'argent et de sang (2023):
    library: Séries TV
    media_directory: /config/cards/Of Money and Blood (2023) [imdb-tt28494836]
  Daria (1997):
    library: Séries TV
    media_directory: /config/cards/Daria (1997) [imdb-tt0118298]
  De la terre à la lune (1998):
    library: Séries TV
    media_directory: /config/cards/From the Earth to the Moon (1998) [imdb-tt0120570]
  Dead Like Me (2003):
    library: Séries TV
    media_directory: /config/cards/Dead Like Me (2003) [imdb-tt0348913]
  Dead Pixels (2019):
    library: Séries TV
    media_directory: /config/cards/Dead Pixels (2019) [imdb-tt7559438]
  Dead Still (2020):
    library: Séries TV
    media_directory: /config/cards/Dead Still (2020) [imdb-tt10413648]
  Dexter (2006):
    library: Séries TV
    media_directory: /config/cards/Dexter (2006) [imdb-tt0773262]
  'Dexter : New Blood (2021)':
    library: Séries TV
    media_directory: /config/cards/Dexter - New Blood (2021) [imdb-tt14164730]
  Dix pour cent (2015):
    library: Séries TV
    media_directory: /config/cards/Call My Agent! (FR) (2015) [imdb-tt4277922]
  Doctor Who (1963):
    library: Séries TV
    media_directory: /config/cards/Doctor Who (1963) [imdb-tt0056751]
    card_type: fade
    extras:
      logo: /config/source/Doctor Who (1963)/logo.png
  Doctor Who (2005):
    library: Séries TV
    media_directory: /config/cards/Doctor Who (2005) [imdb-tt0436992]
  Dopesick (2021):
    library: Séries TV
    media_directory: /config/cards/Dopesick (2021) [imdb-tt9174558]
  Downton Abbey (2010):
    library: Séries TV
    media_directory: /config/cards/Downton Abbey (2010) [imdb-tt1606375]
  Dr House (2004):
    library: Séries TV
    media_directory: /config/cards/House (2004) [imdb-tt0412142]
  Dune (2000):
    library: Séries TV
    media_directory: /config/cards/Dune (2000) [imdb-tt0142032]
    card_type: fade
    extras:
      logo: /config/source/Dune (2000)/logo.png
  Défendre Jacob (2020):
    library: Séries TV
    media_directory: /config/cards/Defending Jacob (2020) [imdb-tt2304589]
  Désenchantée (2018):
    library: Séries TV
    media_directory: /config/cards/Disenchantment (2018) [imdb-tt5363918]
    episode_text_format: Chapter {abs_number}
  Engrenages (2005):
    library: Séries TV
    media_directory: /config/cards/Spiral (2005) [imdb-tt0477507]
  Episodes (2011):
    library: Séries TV
    media_directory: /config/cards/Episodes (2011) [imdb-tt1582350]
  Euphoria (2019):
    library: Séries TV
    media_directory: /config/cards/Euphoria (US) (2019) [imdb-tt8772296]
  Falcon et le Soldat de l'hiver (2021):
    library: Séries TV
    media_directory: /config/cards/The Falcon and the Winter Soldier (2021) [imdb-tt9208876]
  Fargo (2014):
    library: Séries TV
    media_directory: /config/cards/Fargo (2014) [imdb-tt2802850]
  Faux-semblants (2023):
    library: Séries TV
    media_directory: /config/cards/Dead Ringers (2023) [imdb-tt12923632]
  For All Mankind (2019):
    library: Séries TV
    media_directory: /config/cards/For All Mankind (2019) [imdb-tt7772588]
  'Formula 1 : Pilotes de leur destin (2019)':
    library: Séries TV
    media_directory: /config/cards/Formula 1 - Drive to Survive (2019) [imdb-tt8289930]
  Friends (1994):
    library: Séries TV
    media_directory: /config/cards/Friends (1994) [imdb-tt0108778]
  Futurama (1999):
    library: Séries TV
    media_directory: /config/cards/Futurama (1999) [imdb-tt0149460]
  Game of Thrones (2011):
    library: Séries TV
    media_directory: /config/cards/Game of Thrones (2011) [imdb-tt0944947]
  Gen V (2023):
    library: Séries TV
    media_directory: /config/cards/Gen V (2023) [imdb-tt13159924]
  Germinal (2021):
    library: Séries TV
    media_directory: /config/cards/Germinal (2021) [imdb-tt10133336]
  Gilmore Girls (2000):
    library: Séries TV
    media_directory: /config/cards/Gilmore Girls (2000) [imdb-tt0238784]
  'Gilmore Girls : Une nouvelle année (2016)':
    library: Séries TV
    media_directory: /config/cards/Gilmore Girls - A Year in the Life (2016) [imdb-tt5435008]
  Good Omens (2019):
    library: Séries TV
    media_directory: /config/cards/Good Omens (2019) [imdb-tt1869454]
  'HPI : Haut Potentiel Intellectuel (2021)':
    library: Séries TV
    media_directory: /config/cards/HPI (2021) [imdb-tt14060708]
  Hard (2008):
    library: Séries TV
    media_directory: /config/cards/Hard (2008) [imdb-tt1254019]
  Hatufim, prisonniers de guerre (2010):
    library: Séries TV
    media_directory: /config/cards/Prisoners of War (2010) [imdb-tt1676462]
  Hawkeye (2021):
    library: Séries TV
    media_directory: /config/cards/Hawkeye (2021) [imdb-tt10160804]
  Hello Tomorrow! (2023):
    library: Séries TV
    media_directory: /config/cards/Hello Tomorrow! (2023) [imdb-tt14596212]
  Hijack (2023):
    library: Séries TV
    media_directory: /config/cards/Hijack (2023) [imdb-tt19854762]
  Hippocrate (2018):
    library: Séries TV
    media_directory: /config/cards/Hippocrate (2018) [imdb-tt9350920]
  Homeland (2011):
    library: Séries TV
    media_directory: /config/cards/Homeland (2011) [imdb-tt1796960]
  House of the Dragon (2022):
    library: Séries TV
    media_directory: /config/cards/House of the Dragon (2022) [imdb-tt11198330]
  How I Met Your Mother (2005):
    library: Séries TV
    media_directory: /config/cards/How I Met Your Mother (2005) [imdb-tt0460649]
  Infiniti (2022):
    library: Séries TV
    media_directory: /config/cards/Infiniti (2022) [imdb-tt14902026]
  Invasion (2021):
    library: Séries TV
    media_directory: /config/cards/Invasion (2021) [imdb-tt9737326]
  Jack Ryan (2018):
    library: Séries TV
    media_directory: /config/cards/Tom Clancy's Jack Ryan (2018) [imdb-tt5057054]
  Je s'appelle Groot (2022):
    library: Séries TV
    media_directory: /config/cards/I Am Groot (2022) [imdb-tt13623148]
  Kaamelott (2005):
    library: Séries TV
    media_directory: /config/cards/Kaamelott (2005) [imdb-tt0441059]
  L'Affaire d'Outreau (2023):
    library: Séries TV
    media_directory: /config/cards/The Outreau affair (2023) [imdb-]
  L'Hôpital et ses fantômes (1994):
    library: Séries TV
    media_directory: /config/cards/The Kingdom (1994) [imdb-tt0108906]
  La Diplomate (2023):
    library: Séries TV
    media_directory: /config/cards/The Diplomat (2023) [imdb-tt17491088]
  La Fabuleuse Mme Maisel (2017):
    library: Séries TV
    media_directory: /config/cards/The Marvelous Mrs. Maisel (2017) [imdb-tt5788792]
  La Ferme de Clarkson (2021):
    library: Séries TV
    media_directory: /config/cards/Clarkson's Farm (2021) [imdb-tt10541088]
  La Flamme (2020):
    library: Séries TV
    media_directory: /config/cards/La Flamme (2020) [imdb-tt13286778]
  La Petite Fille sous la neige (2023):
    library: Séries TV
    media_directory: /config/cards/The Snow Girl (2023) [imdb-tt15787870]
  La nuit où Laurier Gaudreault s'est réveillé (2022):
    library: Séries TV
    media_directory: /config/cards/The Night Logan Woke Up (2022) [imdb-tt13527546]
  Landscapers (2021):
    library: Séries TV
    media_directory: /config/cards/Landscapers (2021) [imdb-tt11471892]
  Le Bureau des légendes (2015):
    library: Séries TV
    media_directory: /config/cards/The Bureau (2015) [imdb-tt4063800]
  Le Flambeau, les aventuriers de Chupacabra (2022):
    library: Séries TV
    media_directory: /config/cards/Le Flambeau, les aventuriers de Chupacabra (2022)
      [imdb-tt20723358]
  Le Livre de Boba Fett (2021):
    library: Séries TV
    media_directory: /config/cards/The Book of Boba Fett (2021) [imdb-tt13668894]
    card_type: star wars
  Le Maître du Haut Château (2015):
    library: Séries TV
    media_directory: /config/cards/The Man in the High Castle (2015) [imdb-tt1740299]
  'Le Seigneur des anneaux : Les Anneaux de pouvoir (2022)':
    library: Séries TV
    media_directory: /config/cards/The Lord of the Rings - The Rings of Power (2022)
      [imdb-tt7631058]
  Les Désastreuses aventures des orphelins Baudelaire (2017):
    library: Séries TV
    media_directory: /config/cards/A Series of Unfortunate Events (2017) [imdb-tt4834206]
  Les Enfants de Dune (2003):
    library: Séries TV
    media_directory: /config/cards/Children of Dune (2003) [imdb-tt0287839]
    card_type: fade
    extras:
      logo: /config/source/Les Enfants de Dune (2003)/logo.png
  Les Gouttes de Dieu (2023):
    library: Séries TV
    media_directory: /config/cards/Drops of God (2023) [imdb-tt15282746]
  Les Mondes engloutis (1985):
    library: Séries TV
    media_directory: /config/cards/Spartakus and the Sun Beneath the Sea (1985) [imdb-tt0212676]
  Loki (2021):
    library: Séries TV
    media_directory: /config/cards/Loki (2021) [imdb-tt9140554]
  Love, Death & Robots (2019):
    library: Séries TV
    media_directory: /config/cards/Love, Death & Robots (2019) [imdb-tt9561862]
  Lucky Hank (2023):
    library: Séries TV
    media_directory: /config/cards/Lucky Hank (2023) [imdb-tt19785210]
  Mad Men (2007):
    library: Séries TV
    media_directory: /config/cards/Mad Men (2007) [imdb-tt0804503]
  Mare of Easttown (2021):
    library: Séries TV
    media_directory: /config/cards/Mare of Easttown (2021) [imdb-tt10155688]
  Mars (2016):
    library: Séries TV
    media_directory: /config/cards/Mars (2016) [imdb-tt4939064]
  Mercredi (2022):
    library: Séries TV
    media_directory: /config/cards/Wednesday [imdb-tt14075552]
  Meurtre au pied du volcan (2014):
    library: Séries TV
    media_directory: /config/cards/The Lava Field (2014) [imdb-tt3655398]
  Miracle Workers (2019):
    library: Séries TV
    media_directory: /config/cards/Miracle Workers (2019) [imdb-tt7529770]
  Modern Family (2009):
    library: Séries TV
    media_directory: /config/cards/Modern Family (2009) [imdb-tt1442437]
  'Monstres & Cie : Au travail (2021)':
    library: Séries TV
    media_directory: /config/cards/Monsters at Work (2021) [imdb-tt8610082]
  'Moochie : Qui a tué Jill Halliburton ? (2023)':
    library: Séries TV
    media_directory: /config/cards/Moochie - Qui a tué Jill Halliburton ! (2023) [imdb-]
  Moon Knight (2022):
    library: Séries TV
    media_directory: /config/cards/Moon Knight (2022) [imdb-tt10234724]
  Mrs. America (2020):
    library: Séries TV
    media_directory: /config/cards/Mrs. America (2020) [imdb-tt9244556]
  Murderville (2022):
    library: Séries TV
    media_directory: /config/cards/Murderville (2022) [imdb-tt15264192]
  'Mythic Quest : Le festin du corbeau (2020)':
    library: Séries TV
    media_directory: /config/cards/Mythic Quest (2020) [imdb-tt8879940]
  'Narcos : Mexico (2018)':
    library: Séries TV
    media_directory: /config/cards/Narcos - Mexico (2018) [imdb-tt8714904]
  Naruto (2002):
    library: Séries TV
    media_directory: /config/cards/Naruto (2002) [imdb-tt0409591]
    card_type: anime
    translation:
      language: ja
      key: kanji
  Normal People (2020):
    library: Séries TV
    media_directory: /config/cards/Normal People (2020) [imdb-tt9059760]
  ONE PIECE (2023):
    library: Séries TV
    media_directory: /config/cards/One Piece (2023) [imdb-tt11737520]
  OVNI(s) (2021):
    library: Séries TV
    media_directory: /config/cards/UFOs (2021) [imdb-tt10768876]
  Obi-Wan Kenobi (2022):
    library: Séries TV
    media_directory: /config/cards/Obi-Wan Kenobi (2022) [imdb-tt8466564]
    card_type: star wars
  One Piece (1999):
    library: Séries TV
    media_directory: /config/cards/One Piece (1999) [imdb-tt0388629]
    card_type: anime
    translation:
      language: ja
      key: kanji
    seasons:
      1: Arc East Blue
      2: Arc Reverse Mountain / Whisky Peak / Little Garden
      3: Arc Île de Drum
      4: Arc Alabasta
      5: Arc Post-Alabasta / Île des chèvres / Île de Ruruka
      6: Arc Skypiea
      7: Arc G-8 / Long Ring Long Land / Ocean's Dream / Le Retour de Foxy
      8: Arc Water Seven
      9: Arc Enies Lobby
      10: Arc Thriller Bark
      11: Arc Archipel de Sabaody
      12: Arc Amazon Lily
      13: Arc Impel Down & Marineford
      14: Arc Île des Hommes-Poissons
      15: Arc Punk Hazard
      16: Arc Dressrosa 1
      17: Arc Dressrosa 2
      18: Arc Zô
      19: Arc Whole Cake Island
      20: Arc Rêverie
      21: Arc Pays des Wa
  Orphan Black (2013):
    library: Séries TV
    media_directory: /config/cards/Orphan Black (2013) [imdb-tt2234222]
  Oussekine (2022):
    library: Séries TV
    media_directory: /config/cards/Oussekine (2022) [imdb-tt14066198]
  Ozark (2017):
    library: Séries TV
    media_directory: /config/cards/Ozark (2017) [imdb-tt5071412]
  PEN15 (2019):
    library: Séries TV
    media_directory: /config/cards/Pen15 (2019) [imdb-tt8324422]
  Pachinko (2022):
    library: Séries TV
    media_directory: /config/cards/Pachinko (2022) [imdb-tt8888462]
  'Parcs nationaux : Ces merveilles du monde (2022)':
    library: Séries TV
    media_directory: /config/cards/Our Great National Parks (2022) [imdb-tt18750552]
  Paris Police 1900 (2021):
    library: Séries TV
    media_directory: /config/cards/Paris Police 1900 (2021) [imdb-tt10840070]
  Paris Police 1905 (2022):
    library: Séries TV
    media_directory: /config/cards/Paris Police 1905 (2022) [imdb-tt25815944]
  Peacemaker (2022):
    library: Séries TV
    media_directory: /config/cards/Peacemaker (2022) [imdb-tt13146488]
  Peaky Blinders (2013):
    library: Séries TV
    media_directory: /config/cards/Peaky Blinders (2013) [imdb-tt2442560]
  Preacher (2016):
    library: Séries TV
    media_directory: /config/cards/Preacher (2016) [imdb-tt5016504]
  'Périphériques : Les Mondes de Flynne (2022)':
    library: Séries TV
    media_directory: /config/cards/The Peripheral (2022) [imdb-tt8291284]
  Rabbit Hole (2023):
    library: Séries TV
    media_directory: /config/cards/Rabbit Hole (2023) [imdb-tt5822112]
  Real Humans (2012):
    library: Séries TV
    media_directory: /config/cards/Real Humans (2012) [imdb-tt2180271]
  Reboot (2022):
    library: Séries TV
    media_directory: /config/cards/Reboot (2022) [imdb-tt15180134]
  Rick et Morty (2013):
    library: Séries TV
    media_directory: /config/cards/Rick and Morty (2013) [imdb-tt2861424]
  Scrubs (2001):
    library: Séries TV
    media_directory: /config/cards/Scrubs (2001) [imdb-tt0285403]
  Secret Invasion (2023):
    library: Séries TV
    media_directory: /config/cards/Secret Invasion (2023) [imdb-tt13157618]
  Sentinelles (2022):
    library: Séries TV
    media_directory: /config/cards/Sentinels (2022) [imdb-tt18549982]
  Severance (2022):
    library: Séries TV
    media_directory: /config/cards/Severance (2022) [imdb-tt11280740]
  Sex Education (2019):
    library: Séries TV
    media_directory: /config/cards/Sex Education (2019) [imdb-tt7767422]
  'She-Hulk : Avocate (2022)':
    library: Séries TV
    media_directory: /config/cards/Marvel's She-Hulk [imdb-tt10857160]
  Sherlock (2010):
    library: Séries TV
    media_directory: /config/cards/Sherlock (2010) [imdb-tt1475582]
  Shining Girls (2022):
    library: Séries TV
    media_directory: /config/cards/Shining Girls (2022) [imdb-tt2953250]
  Silicon Valley (2014):
    library: Séries TV
    media_directory: /config/cards/Silicon Valley (2014) [imdb-tt2575988]
  Silo (2023):
    library: Séries TV
    media_directory: /config/cards/Silo (2023) [imdb-tt14688458]
  Six Feet Under (2001):
    library: Séries TV
    media_directory: /config/cards/Six Feet Under (2001) [imdb-tt0248654]
  Slow Horses (2022):
    library: Séries TV
    media_directory: /config/cards/Slow Horses (2022) [imdb-tt5875444]
  Smallville (2001):
    library: Séries TV
    media_directory: /config/cards/Smallville (2001) [imdb-tt0279600]
  Sous contrôle (2023):
    library: Séries TV
    media_directory: /config/cards/Sous contrôle (2023) [imdb-tt27012297]
  Space Force (2020):
    library: Séries TV
    media_directory: /config/cards/Space Force (2020) [imdb-tt9612516]
  Squid Game (2021):
    library: Séries TV
    media_directory: /config/cards/Squid Game (2021) [imdb-tt10919420]
  'Star Wars : Andor (2022)':
    library: Séries TV
    media_directory: /config/cards/Andor (2022) [imdb-tt9253284]
    card_type: star wars
  Station Eleven (2021):
    library: Séries TV
    media_directory: /config/cards/Station Eleven (2021) [imdb-tt10574236]
  Stranger Things (2016):
    library: Séries TV
    media_directory: /config/cards/Stranger Things (2016) [imdb-tt4574334]
  Succession (2018):
    library: Séries TV
    media_directory: /config/cards/Succession (2018) [imdb-tt7660850]
  Super Pumped (2022):
    library: Séries TV
    media_directory: /config/cards/Super Pumped (2022) [imdb-tt11173006]
  Supercopter (1984):
    library: Séries TV
    media_directory: /config/cards/Airwolf (1984) [imdb-tt0086662]
  Sur ordre de Dieu (2022):
    library: Séries TV
    media_directory: /config/cards/Under the Banner of Heaven (2022) [imdb-tt1998372]
  Sur écoute (2002):
    library: Séries TV
    media_directory: /config/cards/The Wire (2002) [imdb-tt0306414]
  Tales from the Loop (2020):
    library: Séries TV
    media_directory: /config/cards/Tales from the Loop (2020) [imdb-tt8741290]
  Tapie (2023):
    library: Séries TV
    media_directory: /config/cards/Tapie (2023) [imdb-tt11212810]
  'Terminator : Les Chroniques de Sarah Connor (2008)':
    library: Séries TV
    media_directory: /config/cards/Terminator - The Sarah Connor Chronicles (2008)
      [imdb-tt0851851]
  That '70s Show (1998):
    library: Séries TV
    media_directory: /config/cards/That '70s Show (1998) [imdb-tt0165598]
  'The Bear : sur place ou à emporter (2022)':
    library: Séries TV
    media_directory: /config/cards/The Bear (2022) [imdb-tt14452776]
  The Beatles - Get Back (2021):
    library: Séries TV
    media_directory: /config/cards/The Beatles - Get Back (2021) [imdb-tt9735318]
  The Big Bang Theory (2007):
    library: Séries TV
    media_directory: /config/cards/The Big Bang Theory (2007) [imdb-tt0898266]
  The Boys (2019):
    library: Séries TV
    media_directory: /config/cards/The Boys (2019) [imdb-tt1190634]
  The Bridge (2011):
    library: Séries TV
    media_directory: /config/cards/The Bridge (2011) [imdb-tt1733785]
  The Crown (2016):
    library: Séries TV
    media_directory: /config/cards/The Crown (2016) [imdb-tt4786824]
  The Dropout (2022):
    library: Séries TV
    media_directory: /config/cards/The Dropout (2022) [imdb-tt10166622]
  The Exchange (2023):
    library: Séries TV
    media_directory: /config/cards/The Exchange (2023) [imdb-tt22497928]
  The First (2018):
    library: Séries TV
    media_directory: /config/cards/The First (2018) [imdb-tt7412482]
  The Good Place (2016):
    library: Séries TV
    media_directory: /config/cards/The Good Place (2016) [imdb-tt4955642]
  The Grand Tour (2016):
    library: Séries TV
    media_directory: /config/cards/The Grand Tour (2016) [imdb-tt5712554]
  The Handmaid's Tale - La servante écarlate (2017):
    library: Séries TV
    media_directory: /config/cards/The Handmaid's Tale (2017) [imdb-tt5834204]
  The L Word (2004):
    library: Séries TV
    media_directory: /config/cards/The L Word (2004) [imdb-tt0330251]
  The Last of Us (2023):
    library: Séries TV
    media_directory: /config/cards/The Last of Us (2023) [imdb-tt3581920]
  The Mandalorian (2019):
    library: Séries TV
    media_directory: /config/cards/The Mandalorian (2019) [imdb-tt8111088]
    card_type: star wars
    episode_text_format: Chapter {abs_number}
  The Morning Show (2019):
    library: Séries TV
    media_directory: /config/cards/The Morning Show (2019) [imdb-tt7203552]
  The Office (2005):
    library: Séries TV
    media_directory: /config/cards/The Office (US) (2005) [imdb-tt0386676]
  The Old Man (2022):
    library: Séries TV
    media_directory: /config/cards/The Old Man (2022) [imdb-tt5645432]
  The Playlist (2022):
    library: Séries TV
    media_directory: /config/cards/The Playlist (2022) [imdb-tt11564258]
  The Staircase (2022):
    library: Séries TV
    media_directory: /config/cards/The Staircase (2022) [imdb-tt11324406]
  The Time Traveler's Wife (2022):
    library: Séries TV
    media_directory: /config/cards/The Time Traveler's Wife (2022) [imdb-tt8783930]
  The Undeclared War (2022):
    library: Séries TV
    media_directory: /config/cards/The Undeclared War (2022) [imdb-tt7939800]
  The White Lotus (2021):
    library: Séries TV
    media_directory: /config/cards/The White Lotus (2021) [imdb-tt13406094]
  The Witcher (2019):
    library: Séries TV
    media_directory: /config/cards/The Witcher (2019) [imdb-tt5180504]
  This England - Les années Boris Johnson (2022):
    library: Séries TV
    media_directory: /config/cards/This England (2022) [imdb-tt12594678]
  Tokyo Vice (2022):
    library: Séries TV
    media_directory: /config/cards/Tokyo Vice (2022) [imdb-tt2887954]
  Top Gear (2002):
    library: Séries TV
    media_directory: /config/cards/Top Gear (2002) [imdb-tt1628033]
  Top of the Lake (2013):
    library: Séries TV
    media_directory: /config/cards/Top of the Lake (2013) [imdb-tt2103085]
  Torchwood (2006):
    library: Séries TV
    media_directory: /config/cards/Torchwood (2006) [imdb-tt0485301]
  Trapped (2015):
    library: Séries TV
    media_directory: /config/cards/Trapped (2015) [imdb-tt3561180]
  True Detective (2014):
    library: Séries TV
    media_directory: /config/cards/True Detective (2014) [imdb-tt2356777]
  Twin Peaks (1990):
    library: Séries TV
    media_directory: /config/cards/Twin Peaks (1990) [imdb-tt0098936]
  Téhéran (2020):
    library: Séries TV
    media_directory: /config/cards/Tehran (2020) [imdb-tt10577736]
  Utopia (2013):
    library: Séries TV
    media_directory: /config/cards/Utopia (2013) [imdb-tt2384811]
  'V : La Bataille finale (1984)':
    library: Séries TV
    media_directory: /config/cards/V - The Final Battle (1984) [imdb-tt0086823]
  'V : La série (1984)':
    library: Séries TV
    media_directory: /config/cards/V (1984) [imdb-tt0086822]
  'V : Les visiteurs (1983)':
    library: Séries TV
    media_directory: /config/cards/V - The Original Miniseries (1983) [imdb-tt0085106]
  Veep (2012):
    library: Séries TV
    media_directory: /config/cards/Veep (2012) [imdb-tt1759761]
  Vikings (2013):
    library: Séries TV
    media_directory: /config/cards/Vikings (2013) [imdb-tt2306299]
  WandaVision (2021):
    library: Séries TV
    media_directory: /config/cards/WandaVision (2021) [imdb-tt9140560]
  Watchmen (2019):
    library: Séries TV
    media_directory: /config/cards/Watchmen (2019) [imdb-tt7049682]
  Wayward Pines (2015):
    library: Séries TV
    media_directory: /config/cards/Wayward Pines (2015) [imdb-tt2618986]
  What If...? (2021):
    library: Séries TV
    media_directory: /config/cards/What If…! (2021) [imdb-tt10168312]
  What We Do in the Shadows (2019):
    library: Séries TV
    media_directory: /config/cards/What We Do in the Shadows (2019) [imdb-tt7908628]
  'Winning Time: The Rise of the Lakers Dynasty (2022)':
    library: Séries TV
    media_directory: /config/cards/Winning Time - The Rise of the Lakers Dynasty (2022)
      [imdb-tt10244600]
  Years and Years (2019):
    library: Séries TV
    media_directory: /config/cards/Years and Years (2019) [imdb-tt8694364]
  Yellowjackets (2021):
    library: Séries TV
    media_directory: /config/cards/Yellowjackets (2021) [imdb-tt11041332]
  Yellowstone (2018):
    library: Séries TV
    media_directory: /config/cards/Yellowstone (2018) [imdb-tt4236770]
  Your Honor (2020):
    library: Séries TV
    media_directory: /config/cards/Your Honor (US) (2020) [imdb-tt7440726]
  À la Maison Blanche (1999):
    library: Séries TV
    media_directory: /config/cards/The West Wing (1999) [imdb-tt0200276]
  Misfits (2009):
    library: Séries TV
    media_directory: /config/cards/Misfits (2009) [imdb-tt1548850]
```

### Debug Log

[maker.log](https://github.com/CollinHeist/TitleCardMaker/files/13215330/maker.log)
