### ISSUE TITLE
BUG - \ua789 character error

### ISSUE THREAD

**Issue by Soitora** [CollinHeist/TitleCardMaker#416]
### Installation

GitHub - master branch

### Describe the Bug

For some series, I get around the inability to use colons, with the \ua789 character, which is a fake colon. This works great in Plex, Jellyfin; you name it! But not in the sync here

### Expected Behavior

It should deciper it, or ignore it

### Steps to reproduce the behavior

1. Name your `Star Wars - The Clone Wars (2008)` to `Star Wars: The Clone Wars (2008)`
2. Now you should see an error

### Screenshots

![image](https://github.com/CollinHeist/TitleCardMaker/assets/10836780/9301226c-0f1f-4300-ad86-c317ef9c6a35)

### Preference File

```yaml
options:
  source: O:/Media/.tcm/Cards/
  series:
  #- O:/Media/.tcm/plex_sync_anime.yml
  - O:/Media/.tcm/plex_sync_series.yml
  #- O:/Media/.tcm/jellyfin_sync_anime.yml
  - O:/Media/.tcm/jellyfin_sync_series.yml
  episode_data_source: plex
  image_source_priority: tmdb, plex, jellyfin
  filename_format: "{full_name} - {season:02}x{episode:02} - {title}"
  season_folder_format: "Season {season:02}"
  
plex:
  url: http://127.0.0.1:32400/
  token: X
  verify_ssl: false
  filesize_limit: 4 MB
  sync:
  - mode: match
    compact_mode: false

  #- file: O:/Media/.tcm/plex_sync_anime.yml
    #libraries:
    #- Anime
    
  - file: O:/Media/.tcm/plex_sync_series.yml
    libraries:
    - Series

jellyfin:
  url: http://127.0.0.1:8096/
  api_key: X
  username: Soitora
  verify_ssl: false
  filesize_limit: 4 MB
  sync:
  - mode: match
    compact_mode: false

  #- file: O:/Media/.tcm/jellyfin_sync_anime.yml
    #libraries:
    #- Anime
    
  - file: O:/Media/.tcm/jellyfin_sync_series.yml
    libraries:
    - Series

tautulli:
  url: http://127.0.0.1:8181/
  api_key: X
  update_script: O:/Media/.tcm/tautulli_update.cmd
  verify_ssl: false
  username: Soitora
  agent_name: Update TitleCardMaker
  script_timeout: 120 

tmdb:
  api_key: X
  retry_count: 5
  mimimum_resolution: 800x400
  skip_localized_images: true
```

### Series YAML

```yaml
'Star Wars: The Clone Wars (2008)':
  library: Series
  media_directory: O:\Media\Series\Star Wars꞉ The Clone Wars (2008) {tvdb-83268}
  card_type: star wars
```

### Debug Log

[INFO] [11-04-23 23:31:10.465] Detected new YAML for "Star Wars: The Clone Wars (2008)" - deleting old cards
[INFO] [11-04-23 23:32:46.200] Loaded 133 cards for "Star Wars: The Clone Wars (2008)"

...

[WARNING] [11-04-23 23:32:51.510] Cannot source episodes for "Star Wars: The Clone Wars (2008)" from plex
[INFO] [11-04-23 23:32:51.528] Detected new YAML for "Star Wars: The Clone Wars (2008)" - deleting old cards
