### ISSUE TITLE
HELP - WebUI not present on Unraid

### ISSUE THREAD

**Issue by rozza591** [CollinHeist/TitleCardMaker#426]
### Installation

Docker - master tag

### Describe your Problem

The documentation on the website states that for the unraid CA install the web interface should be available. This is however dosent seem to be the case. I added in the preferences file manually and the only way I managed to get the docker to launch was to change the ownership to  nobody:users but after this change the log now has no output.

On initial setup I put in the correct permissions, I even tried root permissions but neither worked. I set to set this manually.

### Screenshots

![SCR-20231129-jski](https://github.com/CollinHeist/TitleCardMaker/assets/26328838/2e10a6b5-5386-428a-ba49-24e63e204566)

### Preference File

```yaml
options:
  source: ./source/
  series:
  - ./yaml/sonarr_sync.yml
  filename_format: "{full_name} - S{season:02}E{episode:02}"
  season_folder_format: "Season {season:02}"
  sync_specials: false
  
plex:
  url: http://192.168.1.66:32400/
  token: !secret plex_token

sonarr:
  url: http://192.168.1.66:8989/api/v3/
  api_key: !secret sonarr_api
  sync:
  - file: ./yaml/sonarr_sync.yml
    card_directory: ./cards/
    monitored_only: true
    plex_libraries:
      /media/tv/: TV
      /media/anime/: Anime

tmdb:
  api_key: !secret tmdb_api
```

### Debug Log

No log file was created
