### ISSUE TITLE
Add support for other regional variants of languages

### ISSUE THREAD

**Issue by kvalle22** [CollinHeist/TitleCardMaker#452]
This is in my yml for spanish cards
```
  Standard_es:
    card_type: standard
    tmdb_sync: true
    library: Series
    episode_data_source: plex
    episode_text_format: "Temporada {season_number} • Episodio {episode_number}"
    translation:
    - language: es
      key: preferred_title    
    seasons:
      hide: <<seasonless>>
    defaults:
      seasonless: true
```
and it will produce this card 
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/e64aaf9f-3385-44f1-a335-87b795b4a080)
As you can see the name of the episode in spanish doesn't match the one used to generate the card and this is because I set my Plex library to Mexican Spanish which is the most common among Spanish speakers but the Maker uses plain spanish which defaults to european Spanish (they have their own way to talk but it's only used in Spain!)
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/e1163b85-e32d-4e3a-b464-74fc32a9c2d9)
So I was wondering if the Maker can use other regions for Spanish? I already checked on TMDB and both are supported. 
`es-ES` is the one the Maker uses when I set `language: es`
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/6eb38117-ecd1-4093-94db-0cd332dc2ecb)
and what I'm requesting is for it to be able to use other codes like `es-MX`
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/a65ad089-5863-44d2-9e5c-c6f42f3026da)
This happens in every show so it's not an isolated case. As always thank you for your time and attention!

**Comment by kvalle22** [comment]
@CollinHeist 
I forgot to mention that I already tried to use `es-MX`
```
  BannerTitleCard_es:
    card_type: banner
    tmdb_sync: true
    library: Series
    episode_data_source: plex
    episode_text_format: "Temporada {season_number} \n Episodio {episode_number}"
    translation:
    - language: es-MX
      key: preferred_title    
    extras:
      alternate_color: rgb(55, 113, 199)
    seasons:
      hide: <<seasonless>>
    defaults:
      seasonless: true
```
but no error has ocurred and the Maker uses `es-ES` to translate the titles

**Comment by CollinHeist** [comment]
@kvalle22 If you want to switch to the `develop` branch/tag, try `es-MX` and let me know if it works. You'll need to remove any existing translations from the data file.

**Comment by kvalle22** [comment]
@CollinHeist what do you mean by remove any existing translations from the data file?. I created a new folder cloned the `develop` branch and set everything again. I made sure to change all `es` to `es-MX` before running the script for the first time sadly nothing has changed the outcome is the same translation.
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/649d0023-1da5-41d3-ac7f-bb85e63797e5)

**Comment by CollinHeist** [comment]
> what do you mean by remove any existing translations from the data file?

You can read about data files [here](https://github.com/CollinHeist/TitleCardMaker/wiki/Data-Files). But basically you need to remove the translation so TCM can re-add it.

Would you grab the latest changes on `develop` and try once more

**Comment by kvalle22** [comment]
@CollinHeist 😎
Success!
![image](https://github.com/CollinHeist/TitleCardMaker/assets/26128231/65bce2d1-101d-4cf2-a427-8b291eada4e1)

**Comment by CollinHeist** [comment]
FYI, you can avoid translations, and the reliance on TMDb, completely by just setting your episode data source to Plex - it will use your localized episode titles automatically

**Comment by kvalle22** [comment]
@CollinHeist 
```
  Standard_es:
    card_type: standard
    tmdb_sync: false
    library: Series
    episode_data_source: plex
    episode_text_format: "Temporada {season_number} • Episodio {episode_number}"
    translation:
    - language: es-MX
      key: preferred_title    
    seasons:
      hide: <<seasonless>>
    defaults:
      seasonless: true
```

1. If I understand correctly for me to use plex titles I have to `tmdb_sync: false` and `episode_data_source: plex` ?
2. What if Plex grabs titles like `'TBA'` when an episode just comes out but in TMDB it already has the correct title, so in this case if the Maker uses the data from plex then the newly created card will have `'TBA'` as title am I right?
