### ISSUE TITLE
BUG - the tmdb logo_language_priority configuration for "fr" no longer works

### ISSUE THREAD

**Issue by Derekcde** [CollinHeist/TitleCardMaker#462]
### Installation

Docker - master tag

### Describe the Bug

Hello, 
since the last update I have this error:
```
[INFO] Read preference file "/config/preferences.yml"
[CRITICAL] Invalid TMDb logo language codes - must be comma-separated list of any of the following: "ar", "ar-AE", "ar-SA", "bg", "ca", "cn-CN", "cs", "da", "de-AT", "de-CH", "de-DE", "el", "en", "es-ES", "es-MX", "fa", "fi", "fr-CA", "fr-FR", "he", "hi", "hu", "id", "it-IT", "it-CH", "ja", "ka", "ko", "lb", "lt", "lv", "my", "nb-NO", "nl-BE", "nl-NL", "nn-NO", "ms-BN", "ms-MY", "ms-SG", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sr-RS", "sv-FI", "sv-SE", "th", "tr", "uk", "uz-UZ", "vi", "zh", "zh-CN", "zh-HK", "zh-SG"
[CRITICAL] Preference file is invalid
```

So I tried to put fr-FR but I still get the same error

[**it seems that it dates from this commit**](https://github.com/CollinHeist/TitleCardMaker/commit/4a75eff132a67153804fbbb78b84fcbec39cae00)

On the TMDb site they say, perhaps this would be the cause of the error?: 

> > ISO 3166-1
> You'll usually find our language codes mated to a country code in the format of en-US. The country codes in use here are [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
> 
> 📘
> Note
> 
> Images do not yet support the language-COUNTRY notation. This will be improved in the future. Take a read through the [image language](https://developer.themoviedb.org/docs/image-languages) documentation to learn how to partly get around this limitation.

### Preference File

```yaml
# preferences.yml
options:
  source: /config/source/
  series: /config/yaml/sync_plex_seriestv.yml
  card_type: standard
  episode_data_source: plex
  image_source_priority: plex, tmdb
  filename_format: "{full_name} - S{season:02}E{episode:02} - {title}"
  validate_fonts: true
  season_folder_format: "Season {season:02}"
  sync_specials: true
  language_codes: 
  - fr
plex:
  url: http://xxxxxxx:xxxxxxx/
  verify_ssl: true
  token: xxxxxxxxxxxxx
  watched_style: unique
  unwatched_style: blur
  integrate_with_pmm_overlays: true
  integrate_with_kometa: true
  sync:
    file: /config/yaml/sync_plex_seriestv.yml
    card_directory: /config/cards
    library_name: Séries TV
    mode: match
    compact_mode: true
    add_template: global_template
tautulli:
  url: http://xxxxxx:xxxx/
  verify_ssl: true
  api_key: xxxxxxxxxxxxxxxx
  update_script: /tautulli/update_card.sh
  username: "xxxxx"
  agent_name: Update TitleCardMaker
  script_timeout: 120 
sonarr:
  url: http://xxxx:xxx/
  verify_ssl: true
  api_key: xxxxxxxxxxxxxxxxx
  # sync:
  # - card_directory: /config/cards/
    # downloaded_only: true
    # mode: match
  # - file: /config/yaml/sync_sonarr_seriestv.yml
    # add_template: global_template
tmdb:
  api_key: xxxxxxxxxxxxxxxx
  retry_count: 3
  logo_language_priority: fr
```

### Debug Log

[INFO] Read preference file "/config/preferences.yml"
[CRITICAL] Invalid TMDb logo language codes - must be comma-separated list of any of the following: "ar", "ar-AE", "ar-SA", "bg", "ca", "cn-CN", "cs", "da", "de-AT", "de-CH", "de-DE", "el", "en", "es-ES", "es-MX", "fa", "fi", "fr-CA", "fr-FR", "he", "hi", "hu", "id", "it-IT", "it-CH", "ja", "ka", "ko", "lb", "lt", "lv", "my", "nb-NO", "nl-BE", "nl-NL", "nn-NO", "ms-BN", "ms-MY", "ms-SG", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sr-RS", "sv-FI", "sv-SE", "th", "tr", "uk", "uz-UZ", "vi", "zh", "zh-CN", "zh-HK", "zh-SG"
[CRITICAL] Preference file is invalid
usermod: no changes
[INFO] Read preference file "/config/preferences.yml"
[CRITICAL] Invalid TMDb logo language codes - must be comma-separated list of any of the following: "ar", "ar-AE", "ar-SA", "bg", "ca", "cn-CN", "cs", "da", "de-AT", "de-CH", "de-DE", "el", "en", "es-ES", "es-MX", "fa", "fi", "fr-CA", "fr-FR", "he", "hi", "hu", "id", "it-IT", "it-CH", "ja", "ka", "ko", "lb", "lt", "lv", "my", "nb-NO", "nl-BE", "nl-NL", "nn-NO", "ms-BN", "ms-MY", "ms-SG", "no", "pl", "pt-BR", "pt-PT", "ro", "ru", "sk", "sr-RS", "sv-FI", "sv-SE", "th", "tr", "uk", "uz-UZ", "vi", "zh", "zh-CN", "zh-HK", "zh-SG"
[CRITICAL] Preference file is invalid
