### ISSUE TITLE
BUG - TintedFrameTitleCard - episode_text_font_size only gets applied to 'index' and not 'title'

### ISSUE THREAD

**Issue by Jacob-Lasky** [CollinHeist/TitleCardMaker#471]
### Installation

Docker - master tag

### Describe the Bug

When changing episode text font size, the font size only applies to the index and not the title.

### Expected Behavior

When I read `episode_text_font_size` I believe that the title and the index should both be changed by this setting. When I attempt to change the setting, only the index changes and not the title.

### Steps to reproduce the behavior

Change the series YAML `episode_text_font_size`.

Initial attempt
```
    card_type: blurred border
    extras:
      episode_text_font_size: 10.0
      separator: •
```

Checking to see if the font size will change only for the bottom text.

```
    card_type: blurred border
    extras:
      bottom_element: title
      top_element: index
      episode_text_font_size: 10.0
      separator: •
```

### Screenshots

![image](https://github.com/user-attachments/assets/38a34151-2322-4733-9f20-b593fa1bf126)

![image](https://github.com/user-attachments/assets/60e2b572-3ff1-42f6-801c-58751eb83280)

### Preference File

```yaml
options:
  source: /config/source/
  series:
    - /config/yaml/sonarr_sync.yml
  episode_data_source: sonarr
  filename_format: "{full_name} - S{season:02}E{episode:02}"
  season_folder_format: "Season {season:02}"
  card_type: white border
  
plex:
  url: http://192.168.86.183:32400/
  token: [redacted]
  integrate_with_kometa: true
  verify_ssl: false

jellyfin:
  url: http://192.168.86.183:8096/
  api_key: [redacted]
  username: [redacted]
  verify_ssl: false

sonarr:
  url: http://192.168.86.183:8989/api/v3/
  api_key: [redacted]
  verify_ssl: false
  sync:
    - file: /config/yaml/sonarr_sync.yml
      volumes:
        /data/media/: /media/
      card_directory: /config/cards/
      plex_libraries:
        /data/media/tv/: TV Shows
      compact_mode: false

tmdb:
  api_key: [redacted]

tautulli:
  url: http://192.168.86.183:8181/
  api_key: [redacted]
  update_script: /config/update_card.sh
  verify_ssl: false
  username: [redacted]
```
```


### Series YAML

```yaml
libraries:
  TV Shows:
    path: /config/cards/
    media_server: plex
    plex_name: TV Shows
series:
  Dynasties (2018):
    library: TV Shows
    media_directory: /config/cards/Dynasties (2018) {tvdb-352054}
    card_type: blurred border
    extras:
      episode_text_font_size: 10.0
      separator: •
```
```


### Debug Log

N/A
