### ISSUE TITLE
HELP - Tautulli integration with normal usage

### ISSUE THREAD

**Issue by Jorman** [CollinHeist/TitleCardMaker#493]
### Installation

Docker - develop tag

### Describe your Problem

Hi, I am trying to get the integration with Tautulli to work, to have the modification of the shows seen in a short time, and at the same time use the program in the normal way, so under schedule, however, I have difficulties.
At present, neither method seems to work, although TCM seems to be running correctly.

I'm definitely doing something wrong, but I don't understand what.

### Screenshots

![Image](https://github.com/user-attachments/assets/2584fa62-477b-4f48-af26-d1673fe192f9)
![Image](https://github.com/user-attachments/assets/3f802da5-5d00-44e3-b180-57b6919a1868)

### Preference File

```yaml
options:
  source: /config/source/
  series: /config/plex-serie-tv.yml
  episode_data_source: plex
  image_source_priority: tmdb, plex
  sync_specials: true
  language_codes:
    - it

plex:
  url: ***
  # token: ***
  watched_style: grayscale
  unwatched_style: unique
  sync:
    - mode: match
    - card_directory: /config/cards
    - file: /config/plex-serie-tv.yml
      add_template: default
      libraries:
        - Serie TV

# sonarr:
#   url: ***
#   api_key: ***
#   sync:
#   - card_directory: /config/cards
#     downloaded_only: true
#     monitored_only: false
#     plex_libraries:
#       /data/Multimedia/Serie Tv: Serie TV
#   - file: /config/sonarr-serie-tv.yml
#     series_type: standard

tmdb:
  api_key: ***
  skip_localized_images: true
  logo_language_priority: it-IT, en

tautulli:
  url: ***
  api_key: ***
  update_script: /config/update_card.sh
  verify_ssl: true
  username: Chryses
  agent_name: Update TitleCardMaker
  script_timeout: 120

services:
  plex-title-card-maker:
    image: collinheist/titlecardmaker:develop
    container_name: TitleCardMaker-Test
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TCM_MISSING=/config/missing.yml
      - TCM_TAUTULLI_UPDATE_LIST=/tautulli/update.txt
      - TCM_TAUTULLI_UPDATE_FREQUENCY=60s
      - TCM_RUNTIME=22:00
      - TCM_FREQUENCY=2h
    volumes:
      - ${DOCKER_APPDATA}/plex-title-card-maker/config:/config
      - ${DOCKER_APPDATA}/plex-title-card-maker/log:/maker/logs
      - ${DOCKER_APPDATA}/tautulli:/tautulli
      - ${DATA}:/data
```

### Series YAML

```yaml
templates:
  default:
    episode_text_format: Episodio {episode_number}
    seasons:
      1: Stagione 1
      2: Stagione 2
      3: Stagione 3
      4: Stagione 4
      5: Stagione 5
      6: Stagione 6
      7: Stagione 7
      8: Stagione 8
      9: Stagione 9
      10: Stagione 10
      11: Stagione 11
      12: Stagione 12
      13: Stagione 13
      14: Stagione 14
      15: Stagione 15
      16: Stagione 16
      17: Stagione 17
      18: Stagione 18
      19: Stagione 19
      20: Stagione 20
      21: Stagione 21
      22: Stagione 22
      23: Stagione 23
      24: Stagione 24
      25: Stagione 25
      26: Stagione 26
      27: Stagione 27
      28: Stagione 28
      29: Stagione 29
      30: Stagione 30
      31: Stagione 31
      32: Stagione 32
      33: Stagione 33
      34: Stagione 34
      35: Stagione 35
      36: Stagione 36
      37: Stagione 37
      38: Stagione 38
      39: Stagione 39
      40: Stagione 40
      41: Stagione 41
      42: Stagione 42
      43: Stagione 43
      44: Stagione 44
      45: Stagione 45
      46: Stagione 46
      47: Stagione 47
      48: Stagione 48
      49: Stagione 49
      50: Stagione 50
      51: Stagione 51
      52: Stagione 52
      53: Stagione 53
      54: Stagione 54
      55: Stagione 55
      56: Stagione 56
      57: Stagione 57
      58: Stagione 58
      59: Stagione 59
      60: Stagione 60
      61: Stagione 61
      62: Stagione 62
      63: Stagione 63
      64: Stagione 64
      65: Stagione 65
      66: Stagione 66
      67: Stagione 67
      68: Stagione 68
      69: Stagione 69
      70: Stagione 70
      71: Stagione 71
      72: Stagione 72
      73: Stagione 73
      74: Stagione 74
      75: Stagione 75
      76: Stagione 76
      77: Stagione 77
      78: Stagione 78
      79: Stagione 79
      80: Stagione 80
      81: Stagione 81
      82: Stagione 82
      83: Stagione 83
      84: Stagione 84
      85: Stagione 85
      86: Stagione 86
      87: Stagione 87
      88: Stagione 88
      89: Stagione 89
      90: Stagione 90
      91: Stagione 91
      92: Stagione 92
      93: Stagione 93
      94: Stagione 94
      95: Stagione 95
      96: Stagione 96
      97: Stagione 97
      98: Stagione 98
      99: Stagione 99
series:
  American Ninja Warrior (2009): {library: Serie TV, template: default}
  Britain's Got Talent (2007): {library: Serie TV, template: default}
  Canada's Got Talent (2012): {library: Serie TV, template: default}
  Castle Rock (2018): {library: Serie TV, template: default}
  Colombo (1971): {library: Serie TV, template: default, media_directory: /config/cards/Columbo
      (1968)}
  Constellation (2024): {library: Serie TV, template: default}
  Ellery Queen (1975): {library: Serie TV, template: default}
  France's Got Talent (2006): {library: Serie TV, template: default}
  The Frankenstein Chronicles (2015): {library: Serie TV, template: default}
  From (2022): {library: Serie TV, template: default}
  Hannibal (2013): {library: Serie TV, template: default}
  Harrow (2018): {library: Serie TV, template: default}
  Heroes (2006): {library: Serie TV, template: default}
  Heroes Reborn (2015): {library: Serie TV, template: default}
  Legacies (2018): {library: Serie TV, template: default}
  Limitless con Chris Hemsworth (2022): {library: Serie TV, template: default, media_directory: /config/cards/Limitless
      with Chris Hemsworth (2022)}
  Manifest (2018): {library: Serie TV, template: default}
  Morte e altri dettagli (2024): {library: Serie TV, template: default, media_directory: /config/cards/Death
      and Other Details (2024)}
  Nashville (2012): {library: Serie TV, template: default}
  Only Murders in the Building (2021): {library: Serie TV, template: default}
  Poirot (1989): {library: Serie TV, template: default, media_directory: /config/cards/Agatha
      Christie's Poirot (1989)}
  Project Blue Book (2019): {library: Serie TV, template: default}
  Songland (2019): {library: Serie TV, template: default}
  Spain's Got Talent (2016): {library: Serie TV, template: default}
  Survive (2020): {library: Serie TV, template: default}
  The Terror (2018): {library: Serie TV, template: default}
  Wayward Pines (2015): {library: Serie TV, template: default}
  The Last of Us (2023): {library: Serie TV, template: default}
  Call My Agent - Italia (2023): {library: Serie TV, template: default}
  Breaking Bad (2008): {library: Serie TV, template: default}
  The Night of - Cosa eÌ€ successo quella notte? (2016): {library: Serie TV, template: default,
    media_directory: /config/cards/The Night Of (2016)}
  Yellowjackets (2021): {library: Serie TV, template: default}
libraries:
  Serie TV:
    path: /config/cards
    media_server: plex
```

### Debug Log

[maker.log](https://github.com/user-attachments/files/19097455/maker.log)
