### ISSUE TITLE
Rework data files from .tsv to YAML

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#5]
Datafiles being tab-separated value sheets is a remnant of the project working on exported spreadsheets, and is rather limiting for development

Datafiles should be YAML like the preference/card files, perhaps formatted as:

```YAML
data:
  Season 0:
    1:
      title: When the Future Fights Back
  Season 1:
    1:
      absolute_number: 1
      title: The Rabbit Hole
    # ... 
    6:
      absolute_number: 6
      title:
        - Happy Birthday,
        - Lee Harvey Oswald
```

Where title linebreaks can be manually specified if the title is given as a list (ep 6 of example), otherwise the full title is passed to the `Title` class, and split based on `CardType` attributes.
