### ISSUE TITLE
Improve repeat font specification

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#71]
If you want to specify a custom font for multiple shows, it requires a lot of copy/pasting.

I think some variation to the series yaml files as:

```yaml
libraries:
  # ...

fonts:
  font_label_1:
    size: 110%
    file: # ...
    color: "#ababab"

series:
  series_1:
    year: # ...
    font: font_label_1
```

Could be used (similar to libraries)
