### ISSUE TITLE
Implement YAML templates

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker#90]
Implement the "template" idea (I think from Plex Meta Manager) for series YAML files.

Could use same variable specification as PMM, like:

```yaml
template:
  no_season:
    year: <<year>>
    library: <<library>>
    seasons:
      hide: true

series:
  Series Name:
    template: {name: no_season, year: 2020, library: TV}
```

Would be equivalent to:

```yaml
series:
  Series Name:
    year: 2020
    library: TV
    seasons:
      hide: true
```
